from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = ROOT / "core" / "shared" / "schema.json"

GO_OUTPUT = ROOT / "core" / "bridge" / "app" / "envelope_generated.go"
RUST_OUTPUT = ROOT / "apps" / "cli" / "src" / "envelope_generated.rs"
TS_OUTPUT = ROOT / "apps" / "web" / "lib" / "envelope.generated.ts"


def load_schema() -> dict:
    with SCHEMA_PATH.open("r", encoding="utf-8") as fp:
        return json.load(fp)


def render_go(schema: dict) -> str:
    actions = schema["$defs"]["action"]["enum"]
    statuses = schema["$defs"]["status"]["enum"]
    assistant_session_end_signal = schema["$defs"]["assistantSessionEndSignal"]["properties"]["signal"]["const"]
    schema_id = schema.get("$id", "")

    go_actions = "\n".join(
        f'\tbusAction{action.title().replace("_", "")} = "{action}"' for action in actions
    )
    go_statuses = "\n".join(
        f'\tbusStatus{status.title()} = "{status}"' for status in statuses
    )

    return f"""// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json ({schema_id})

package app

import "encoding/json"

const (
{go_actions}
)

const (
{go_statuses}
)

const busAssistantSessionEndSignal = "{assistant_session_end_signal}"

// assistantSessionEndSignalPayload 对齐 core/shared/schema.json 的 assistantSessionEndSignal。
type assistantSessionEndSignalPayload struct {{
\tSignal  string `json:"signal"`
\tMessage string `json:"message"`
}}

// apiRequest 对齐 core/shared/schema.json 的 requestEnvelope。
type apiRequest struct {{
\tAction  string          `json:"action"`
\tParams  json.RawMessage `json:"params"`
\tTraceID string          `json:"trace_id"`
}}

// apiResponse 对齐 core/shared/schema.json 的 responseEnvelope。
type apiResponse struct {{
\tStatus  string `json:"status"`
\tPayload any    `json:"payload"`
\tError   string `json:"error"`
}}
"""


def render_rust(schema: dict) -> str:
    assistant_session_end_signal = schema["$defs"]["assistantSessionEndSignal"]["properties"]["signal"]["const"]
    schema_id = schema.get("$id", "")

    return f"""// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json ({schema_id})

use anyhow::{{Result, anyhow}};
use serde::{{Deserialize, Serialize}};

pub const ASSISTANT_SESSION_END_SIGNAL: &str = "{assistant_session_end_signal}";

#[derive(Debug, Serialize)]
pub struct ApiRequest<TParams> {{
    pub action: &'static str,
    pub params: TParams,
    pub trace_id: String,
}}

#[derive(Debug, Deserialize)]
pub struct ApiResponse<TPayload> {{
    pub status: String,
    pub payload: Option<TPayload>,
    #[serde(default)]
    pub error: String,
}}

impl<TPayload> ApiResponse<TPayload> {{
    pub fn into_result(self) -> Result<TPayload> {{
        if self.status == "success" {{
            return self
                .payload
                .ok_or_else(|| anyhow!("bridge response payload is missing"));
        }}
        let message = self.error.trim();
        if message.is_empty() {{
            return Err(anyhow!("bridge returned an unknown error"));
        }}
        Err(anyhow!(message.to_string()))
    }}
}}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistantSessionEndSignal {{
    pub signal: String,
    pub message: String,
}}
"""


def render_ts(schema: dict) -> str:
    actions = schema["$defs"]["action"]["enum"]
    statuses = schema["$defs"]["status"]["enum"]
    assistant_session_end_signal = schema["$defs"]["assistantSessionEndSignal"]["properties"]["signal"]["const"]
    schema_id = schema.get("$id", "")

    action_union = " | ".join(f"'{action}'" for action in actions)
    status_union = " | ".join(f"'{status}'" for status in statuses)

    return f"""// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json ({schema_id})

export type BusAction = {action_union};
export type BusStatus = {status_union};
export const ASSISTANT_SESSION_END_SIGNAL = '{assistant_session_end_signal}' as const;

export interface ApiRequest<TParams extends Record<string, unknown>> {{
  action: BusAction;
  params: TParams;
  trace_id: string;
}}

export interface ApiSuccessEnvelope<TPayload> {{
  status: 'success';
  payload: TPayload;
  error: string;
}}

export interface ApiErrorEnvelope {{
  status: 'error';
  payload: Record<string, unknown>;
  error: string;
}}

export type ApiEnvelope<TPayload> = ApiSuccessEnvelope<TPayload> | ApiErrorEnvelope;

export interface AssistantSessionEndSignal {{
  signal: typeof ASSISTANT_SESSION_END_SIGNAL;
  message: string;
}}
"""


def write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    schema = load_schema()

    write_output(GO_OUTPUT, render_go(schema))
    write_output(RUST_OUTPUT, render_rust(schema))
    write_output(TS_OUTPUT, render_ts(schema))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
