package config

func runtimeConfigWithProviders(input runtimeConfigBuildInput, providers []providerConfig) runtimeConfig {
	active := resolveActiveProvider(providers, stringValue(input.FileCfg.ActiveProvider), input.Fallback)
	return normalizeRuntimeConfig(runtimeConfig{
		ProviderName:                   active.Name,
		Provider:                       active.Type.Normalized(),
		APIKey:                         resolveRuntimeAPIKey(active, input.Fallback.APIKey),
		BaseURL:                        resolveRuntimeBaseURL(active.BaseURL, input.Fallback.BaseURL),
		Model:                          resolveRuntimeModel(input.FileCfg, input.Fallback),
		ChatPath:                       resolveRuntimeChatPath(input.FileCfg, input.Fallback),
		ResponseOptions:                input.Settings.ResponseOptions,
		CodexStatelessRetryEnabled:     input.Settings.CodexStatelessRetryEnabled,
		NativePersistent:               resolveRuntimeNativePersistent(input.FileCfg, input.Fallback),
		ProjectRoot:                    resolveRuntimeProjectRoot(input.FileCfg, input.Fallback),
		MaxTurns:                       input.Settings.MaxTurns,
		TaskExecutionTimeoutMS:         input.Settings.TaskExecutionTimeoutMS,
		RelayDefaultStopPolicy:         input.Settings.RelayDefaultStopPolicy,
		RelayDefaultMaxRounds:          input.Settings.RelayDefaultMaxRounds,
		RelayDefaultExecutionTimeoutMS: input.Settings.RelayDefaultExecutionTimeoutMS,
		LLMCompletionRetryCount:        input.Settings.LLMCompletionRetryCount,
		LLMCompletionRetryIntervalMS:   input.Settings.LLMCompletionRetryIntervalMS,
		ModelSelectionEnabled:          !input.Settings.AllowlistOnly,
		ContextWindowTokens:            active.ContextWindowTokens,
		ResponseReserveTokens:          active.ResponseReserveTokens,
		ModelContextWindowTokens:       cloneModelTokenOverrides(active.ModelContextWindowTokens),
		ModelResponseReserveTokens:     cloneModelTokenOverrides(active.ModelResponseReserveTokens),
		WebSearchTavilyURL:             input.Settings.WebSearch.TavilyURL,
		WebSearchExaURL:                input.Settings.WebSearch.ExaURL,
		WebSearchTavilyAPIKey:          input.Settings.WebSearch.TavilyAPIKey,
		WebSearchExaAPIKey:             input.Settings.WebSearch.ExaAPIKey,
		SessionHumanLogFullEnabled:     input.Settings.SessionHumanLogFullEnabled,
		SessionSystemPromptVisible:     input.Settings.SessionSystemPromptVisible,
		AssistantMarkdownEnabled:       input.Settings.AssistantMarkdownEnabled,
		ToolCallCompactOutputEnabled:   input.Settings.ToolCallCompactOutputEnabled,
		MemoryModeEnabled:              input.Settings.MemoryModeEnabled,
		MicrocompactEnabled:            input.Settings.MicrocompactEnabled,
		SessionTitleMode:               input.Settings.SessionTitleMode,
	})
}

func runtimeConfigWithoutProviders(input runtimeConfigBuildInput) runtimeConfig {
	providerName := resolveRuntimeProviderName(input.Fallback)
	return normalizeRuntimeConfig(runtimeConfig{
		ProviderName:                   providerName,
		Provider:                       inferProviderType(providerName, input.Fallback.BaseURL, resolveRuntimeModel(input.FileCfg, input.Fallback)),
		APIKey:                         input.Fallback.APIKey,
		BaseURL:                        input.Fallback.BaseURL,
		Model:                          resolveRuntimeModel(input.FileCfg, input.Fallback),
		ChatPath:                       resolveRuntimeChatPath(input.FileCfg, input.Fallback),
		ResponseOptions:                input.Settings.ResponseOptions,
		CodexStatelessRetryEnabled:     input.Settings.CodexStatelessRetryEnabled,
		NativePersistent:               resolveRuntimeNativePersistent(input.FileCfg, input.Fallback),
		ProjectRoot:                    resolveRuntimeProjectRoot(input.FileCfg, input.Fallback),
		MaxTurns:                       input.Settings.MaxTurns,
		TaskExecutionTimeoutMS:         input.Settings.TaskExecutionTimeoutMS,
		RelayDefaultStopPolicy:         input.Settings.RelayDefaultStopPolicy,
		RelayDefaultMaxRounds:          input.Settings.RelayDefaultMaxRounds,
		RelayDefaultExecutionTimeoutMS: input.Settings.RelayDefaultExecutionTimeoutMS,
		LLMCompletionRetryCount:        input.Settings.LLMCompletionRetryCount,
		LLMCompletionRetryIntervalMS:   input.Settings.LLMCompletionRetryIntervalMS,
		ModelSelectionEnabled:          !input.Settings.AllowlistOnly,
		ContextWindowTokens:            input.Fallback.ContextWindowTokens,
		ResponseReserveTokens:          input.Fallback.ResponseReserveTokens,
		ModelContextWindowTokens:       cloneModelTokenOverrides(input.Fallback.ModelContextWindowTokens),
		ModelResponseReserveTokens:     cloneModelTokenOverrides(input.Fallback.ModelResponseReserveTokens),
		WebSearchTavilyURL:             input.Settings.WebSearch.TavilyURL,
		WebSearchExaURL:                input.Settings.WebSearch.ExaURL,
		WebSearchTavilyAPIKey:          input.Settings.WebSearch.TavilyAPIKey,
		WebSearchExaAPIKey:             input.Settings.WebSearch.ExaAPIKey,
		SessionHumanLogFullEnabled:     input.Settings.SessionHumanLogFullEnabled,
		SessionSystemPromptVisible:     input.Settings.SessionSystemPromptVisible,
		AssistantMarkdownEnabled:       input.Settings.AssistantMarkdownEnabled,
		ToolCallCompactOutputEnabled:   input.Settings.ToolCallCompactOutputEnabled,
		MemoryModeEnabled:              input.Settings.MemoryModeEnabled,
		MicrocompactEnabled:            input.Settings.MicrocompactEnabled,
		SessionTitleMode:               input.Settings.SessionTitleMode,
	})
}
