// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

export type BusAction = 'PING' | 'AGENT_SEND' | 'AGENT_STOP' | 'HUMAN_RESPONSE' | 'CONFIG_GET' | 'CONFIG_UPDATE' | 'TASK_CREATE' | 'TASK_LIST' | 'TASK_SYSTEM_LIST' | 'TASK_GET' | 'TASK_UPDATE' | 'TASK_RUN_NOW' | 'TASK_LOGS' | 'TASK_DELETE' | 'LIST_FILES' | 'READ_FILE' | 'SEARCH_FILES' | 'APPLY_DIFF' | 'EXPORT_FILE' | 'BASH_EXEC' | 'SCRIPT_EXEC' | 'SCREEN_CAPTURE' | 'IMAGE_CROP' | 'OCR_IMAGE' | 'TEXT_INPUT' | 'MOUSE_CLICK' | 'TEMPLATE_MATCH_IMAGE';
export type BusStatus = 'success' | 'error';

export interface ApiRequest<TParams extends Record<string, unknown>> {
  action: BusAction;
  params: TParams;
  trace_id: string;
  request_id?: string;
}

export interface ApiSuccessEnvelope<TPayload> {
  status: 'success';
  payload: TPayload;
  error: string;
  request_id?: string;
}

export interface ApiErrorEnvelope {
  status: 'error';
  payload: Record<string, unknown>;
  error: string;
  request_id?: string;
}

export type ApiEnvelope<TPayload> = ApiSuccessEnvelope<TPayload> | ApiErrorEnvelope;

export interface AssistantSessionEndSignal {
  signal: 'END_SESSION';
  message: string;
}

export interface AgentRequest {
  message: string;
  session_id?: string;
  trace_id?: string;
}

export interface AskHumanOption {
  label: string;
  allow_custom?: boolean;
}

export interface AgentSendSuccessResponse {
  message: string;
  session_id: string;
  session_ended: boolean;
  mode?: 'pro' | 'prox';
  iteration_count?: number;
  stopped_by?: string;
  final_change_log?: string;
  iteration_summary?: Record<string, unknown>[];
  session_end?: AssistantSessionEndSignal | null;
}

export interface AgentSendAwaitingHumanResponse {
  status: 'awaiting_human';
  session_id: string;
  question_id: string;
  prompt: string;
  selection_mode?: 'single' | 'multiple';
  options?: AskHumanOption[];
}

export interface AgentStopResponsePayload {
  status: 'stopped' | 'not_running';
  message: string;
}

export interface HumanResponseRequest {
  session_id: string;
  question_id: string;
  answer: string;
  cancelled?: boolean;
}

export interface HumanResponseAck {
  session_id: string;
  question_id: string;
  accepted: boolean;
}

export interface SessionImageContent {
  path?: string;
  url?: string;
  mime_type?: string;
  width?: number;
  height?: number;
  sha256?: string;
  bytes?: number;
}

export interface SessionFileContent {
  artifact_id: string;
  name: string;
  mime_type?: string;
  bytes?: number;
  sha256?: string;
  download_url: string;
  source_path?: string;
  note?: string;
}

export interface SessionContentPart {
  type: string;
  text?: string;
  image?: SessionImageContent | null;
  file?: SessionFileContent | null;
}

export interface SessionToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

export interface SessionToolResult {
  status: 'success' | 'error';
  tool: string;
  trace_id?: string;
  output?: string;
  error?: string;
}

export interface SessionHumanInteraction {
  question_id: string;
  prompt: string;
  selection_mode?: 'single' | 'multiple';
  options?: AskHumanOption[];
  answer?: string;
}

export interface SessionMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  text?: string;
  content?: SessionContentPart[];
  tool_calls?: SessionToolCall[];
  tool_result?: SessionToolResult | null;
  human_interaction?: SessionHumanInteraction | null;
  tool_call_id?: string;
}

export interface SessionMetadata {
  id: string;
  created_at: string;
  updated_at: string;
  message_count: number;
  token_count: number;
}

export interface SessionDetail {
  id: string;
  messages: SessionMessage[];
  created_at: string;
  updated_at: string;
  token_count: number;
}

export interface BridgeConfig {
  provider: string;
  provider_type: 'openai' | 'anthropic' | 'custom' | 'codex';
  base_url: string;
  model: string;
  chat_path: string;
  api_key_set: boolean;
  model_selection_enabled: boolean;
  graphql_default_source: string;
  graphql_sources: GraphQLSourceResponse[];
  web_search_tavily_api_key_set: boolean;
  web_search_exa_api_key_set: boolean;
}

export interface ConfigUpdate {
  provider?: string;
  api_key?: string;
  base_url?: string;
  model?: string;
  chat_path?: string;
  graphql_default_source?: string;
  graphql_sources?: GraphQLSourceInput[];
  graphql_source_upsert?: GraphQLSourceInput;
  web_search_tavily_api_key?: string;
  web_search_exa_api_key?: string;
  trace_id?: string;
}

export interface GraphQLDomainResponse {
  name: string;
  description?: string;
  root_queries: string[];
  types?: string[];
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
}

export interface GraphQLSourceResponse {
  name: string;
  description?: string;
  endpoint: string;
  schema_path: string;
  timeout_ms: number;
  max_response_bytes: number;
  max_depth: number;
  max_fields: number;
  max_root_fields: number;
  max_fragments: number;
  headers?: Record<string, unknown>;
  api_key_set: boolean;
  domains?: GraphQLDomainResponse[];
}

export interface GraphQLDomainInput {
  name: string;
  description?: string;
  root_queries: string[];
  types?: string[];
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
}

export interface GraphQLSourceInput {
  name: string;
  description?: string;
  endpoint: string;
  api_key?: string;
  schema_path: string;
  timeout_ms?: number;
  max_response_bytes?: number;
  headers?: Record<string, unknown>;
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
  max_fragments?: number;
  domains?: GraphQLDomainInput[];
}

export interface ProviderConfig {
  name: string;
  type: 'openai' | 'anthropic' | 'custom' | 'codex';
  base_url: string;
  models?: string[];
  context_window_tokens?: number;
  response_reserve_tokens?: number;
  model_context_window_tokens?: Record<string, unknown>;
  model_response_reserve_tokens?: Record<string, unknown>;
  api_key_set: boolean;
}

export interface ProviderConfigInput {
  name: string;
  type: 'openai' | 'anthropic' | 'custom' | 'codex';
  base_url?: string;
  api_key?: string;
  models?: string[];
  context_window_tokens?: number;
  response_reserve_tokens?: number;
  model_context_window_tokens?: Record<string, unknown>;
  model_response_reserve_tokens?: Record<string, unknown>;
  trace_id?: string;
}

export interface ProviderListResponse {
  providers: ProviderConfig[];
  active_provider: string;
}

export interface SetActiveProviderRequest {
  name: string;
  trace_id?: string;
}

export type AgentSendResponse = AgentSendSuccessResponse | AgentSendAwaitingHumanResponse;
