// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

export type BusAction = 'AGENT_SEND' | 'AGENT_STOP' | 'HUMAN_RESPONSE' | 'CONFIG_GET' | 'CONFIG_UPDATE' | 'TASK_CREATE' | 'TASK_LIST' | 'TASK_GET' | 'TASK_UPDATE' | 'TASK_RUN_NOW' | 'TASK_LOGS' | 'TASK_DELETE' | 'RSS_INBOX_POLL' | 'RSS_INBOX_LIST' | 'RSS_INBOX_GET' | 'RSS_INBOX_GROUPS' | 'RSS_BRIEFING_BUILD' | 'RSS_BRIEFING_GET';
export type BusStatus = 'success' | 'error';

export interface ApiRequest<TParams extends Record<string, unknown>> {
  action: BusAction;
  params: TParams;
  trace_id: string;
  request_id?: string;
}

export interface ApiSuccessEnvelope<TPayload> {
  status: 'success';
  payload: TPayload;
  error: string;
  request_id?: string;
}

export interface ApiErrorEnvelope {
  status: 'error';
  payload: Record<string, unknown>;
  error: string;
  request_id?: string;
}

export type ApiEnvelope<TPayload> = ApiSuccessEnvelope<TPayload> | ApiErrorEnvelope;

export interface AssistantSessionEndSignal {
  signal: 'END_SESSION';
  message: string;
}

export interface AgentRequest {
  mode?: 'plan';
  message?: string;
  images?: SessionImageContent[];
  session_id?: string;
  trace_id?: string;
}

export interface AgentIterationSummaryItem {
  iteration: number;
  did: string;
  remaining: string;
  completed?: boolean;
  trace_id?: string;
  recorded_at?: string;
  final_change_log?: string;
}

export interface AskHumanOption {
  label: string;
  allow_custom?: boolean;
}

export interface AgentSendSuccessResponse {
  message: string;
  session_id: string;
  session_ended: boolean;
  mode?: 'pro' | 'prox' | 'plan';
  iteration_count?: number;
  stopped_by?: string;
  final_change_log?: string;
  iteration_summary?: AgentIterationSummaryItem[];
  session_end?: AssistantSessionEndSignal | null;
}

export interface AgentSendAwaitingHumanResponse {
  status: 'awaiting_human';
  session_id: string;
  question_id: string;
  prompt: string;
  selection_mode?: 'single' | 'multiple';
  options?: AskHumanOption[];
}

export interface AgentStopResponsePayload {
  status: 'stopped' | 'not_running';
  message: string;
}

export interface HumanResponseRequest {
  session_id: string;
  question_id: string;
  answer: string;
  cancelled?: boolean;
}

export interface HumanResponseAck {
  session_id: string;
  question_id: string;
  accepted: boolean;
}

export interface AgentStreamEvent {
  id: string;
  step_id: string;
  trace_id: string;
  session_id?: string;
  turn: number;
  type: 'run_started' | 'completion_delta' | 'tool_call_started' | 'tool_call_finished' | 'awaiting_human' | 'message' | 'done' | 'error';
  payload: Record<string, unknown>;
  at?: string;
}

export interface SessionImageContent {
  path?: string;
  url?: string;
  mime_type?: string;
  width?: number;
  height?: number;
  sha256?: string;
  bytes?: number;
}

export interface SessionFileContent {
  artifact_id: string;
  name: string;
  mime_type?: string;
  bytes?: number;
  sha256?: string;
  download_url: string;
  source_path?: string;
  note?: string;
}

export interface SessionPushEvent {
  id: string;
  type: 'assistant_message' | 'awaiting_human' | 'run_started' | 'completion_delta' | 'tool_call_started' | 'tool_call_finished' | 'error' | 'done';
  trace_id?: string;
  session_id: string;
  payload: Record<string, unknown>;
  at?: string;
}

export interface AgentRunStartedPayload {
  session_id?: string;
}

export interface SessionContentPart {
  type: string;
  text?: string;
  image?: SessionImageContent | null;
  file?: SessionFileContent | null;
}

export interface AgentCompletionDeltaPayload {
  kind: 'text' | 'tool_call_start' | 'tool_call_delta' | 'tool_call_end';
  text?: string;
  tool_call_index?: number;
  tool_call_id?: string;
  tool_name?: string;
  arguments_fragment?: string;
}

export interface SessionToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

export interface AgentToolCallStartedPayload {
  tool?: string;
  tool_call_id?: string;
}

export interface SessionToolResult {
  status: 'success' | 'error';
  tool: string;
  trace_id?: string;
  output?: string;
  error?: string;
}

export interface AgentToolCallFinishedPayload {
  tool?: string;
  tool_call_id?: string;
  status?: string;
  error?: string;
}

export interface SessionHumanInteraction {
  question_id: string;
  prompt: string;
  selection_mode?: 'single' | 'multiple';
  options?: AskHumanOption[];
  answer?: string;
}

export interface AgentStreamMessagePayload {
  text: string;
  session_id?: string;
}

export interface SessionMessage {
  index: number;
  role: 'system' | 'internal' | 'user' | 'assistant' | 'tool';
  text?: string;
  content?: SessionContentPart[];
  tool_calls?: SessionToolCall[];
  tool_result?: SessionToolResult | null;
  human_interaction?: SessionHumanInteraction | null;
  tool_call_id?: string;
  in_progress?: boolean;
}

export interface AgentDonePayload {
  session_id?: string;
  session_ended?: boolean;
}

export interface SessionMetadata {
  id: string;
  created_at: string;
  updated_at: string;
  message_count: number;
  token_count: number;
}

export interface SessionMessagePage {
  limit: number;
  before?: number | null;
  start_index?: number | null;
  end_index?: number | null;
  has_more_before: boolean;
  next_before?: number | null;
}

export interface AgentErrorPayload {
  message: string;
  session_id?: string;
  code?: number;
}

export interface SessionDetail {
  id: string;
  messages: SessionMessage[];
  created_at: string;
  updated_at: string;
  message_count: number;
  page: SessionMessagePage;
  token_count: number;
}

export interface BridgeConfig {
  provider: string;
  provider_type: 'openai' | 'anthropic' | 'custom' | 'codex';
  base_url: string;
  model: string;
  chat_path: string;
  api_key_set: boolean;
  model_selection_enabled: boolean;
  graphql_default_source: string;
  graphql_tool_runtime_enabled: boolean;
  graphql_text_sanitize_enabled: boolean;
  graphql_sources: GraphQLSourceResponse[];
  graphql_mutation_policies: GraphQLMutationPolicyResponse[];
  session_human_log_full_enabled: boolean;
  web_rooter_enabled: boolean;
  web_rooter_base_url: string;
  web_rooter_timeout_ms: number;
  web_rooter_api_token_set: boolean;
  web_search_tavily_url: string;
  web_search_exa_url: string;
  web_search_tavily_api_key_set: boolean;
  web_search_exa_api_key_set: boolean;
}

export interface SessionPushAssistantMessagePayload {
  message: string;
  session_ended: boolean;
  session_end?: AssistantSessionEndSignal | null;
}

export interface ConfigUpdate {
  provider?: string;
  api_key?: string;
  base_url?: string;
  model?: string;
  chat_path?: string;
  graphql_default_source?: string;
  graphql_tool_runtime_enabled?: boolean;
  graphql_text_sanitize_enabled?: boolean;
  graphql_sources?: GraphQLSourceInput[];
  graphql_source_upsert?: GraphQLSourceInput;
  graphql_mutation_policies?: GraphQLMutationPolicyInput[];
  session_human_log_full_enabled?: boolean;
  web_rooter_enabled?: boolean;
  web_rooter_base_url?: string;
  web_rooter_api_token?: string;
  web_rooter_timeout_ms?: number;
  web_search_tavily_url?: string;
  web_search_exa_url?: string;
  web_search_tavily_api_key?: string;
  web_search_exa_api_key?: string;
  trace_id?: string;
}

export interface SessionPushAwaitingHumanPayload {
  question_id: string;
  prompt: string;
  selection_mode?: 'single' | 'multiple';
  options?: AskHumanOption[];
}

export interface GraphQLDomainResponse {
  name: string;
  description?: string;
  root_queries: string[];
  types?: string[];
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
}

export interface GraphQLSourceResponse {
  name: string;
  description?: string;
  endpoint: string;
  schema_path: string;
  timeout_ms: number;
  max_response_bytes: number;
  max_depth: number;
  max_fields: number;
  max_root_fields: number;
  max_fragments: number;
  headers?: Record<string, string>;
  api_key_set: boolean;
  domains?: GraphQLDomainResponse[];
}

export interface GraphQLDomainInput {
  name: string;
  description?: string;
  root_queries: string[];
  types?: string[];
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
}

export interface GraphQLMutationPolicyResponse {
  name: string;
  description?: string;
  source: string;
  domain: string;
  root_mutation: string;
  approval_required?: boolean;
  idempotency_mode: 'header' | 'variable_path';
  idempotency_header?: string;
  idempotency_variable_path?: string;
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
  max_fragments?: number;
}

export interface GraphQLMutationPolicyInput {
  name: string;
  description?: string;
  source: string;
  domain: string;
  root_mutation: string;
  approval_required?: boolean;
  idempotency_mode: 'header' | 'variable_path';
  idempotency_header?: string;
  idempotency_variable_path?: string;
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
  max_fragments?: number;
}

export interface GraphQLSourceInput {
  name: string;
  description?: string;
  endpoint: string;
  api_key?: string;
  schema_path: string;
  timeout_ms?: number;
  max_response_bytes?: number;
  headers?: Record<string, string>;
  max_depth?: number;
  max_fields?: number;
  max_root_fields?: number;
  max_fragments?: number;
  domains?: GraphQLDomainInput[];
}

export interface ProviderConfig {
  name: string;
  type: 'openai' | 'anthropic' | 'custom' | 'codex';
  base_url: string;
  models?: string[];
  context_window_tokens?: number;
  response_reserve_tokens?: number;
  model_context_window_tokens?: Record<string, number>;
  model_response_reserve_tokens?: Record<string, number>;
  api_key_set: boolean;
}

export interface ProviderConfigInput {
  name: string;
  type: 'openai' | 'anthropic' | 'custom' | 'codex';
  base_url?: string;
  api_key?: string;
  models?: string[];
  context_window_tokens?: number;
  response_reserve_tokens?: number;
  model_context_window_tokens?: Record<string, number>;
  model_response_reserve_tokens?: Record<string, number>;
  trace_id?: string;
}

export interface ProviderListResponse {
  providers: ProviderConfig[];
  active_provider: string;
}

export interface SetActiveProviderRequest {
  name: string;
  trace_id?: string;
}

export interface WorkflowNode {
  id: string;
  type: 'start' | 'tool' | 'llm' | 'agent' | 'if' | 'loop' | 'end';
  start?: WorkflowStartNode;
  tool?: WorkflowToolNode;
  llm?: WorkflowLLMNode;
  agent?: WorkflowAgentNode;
  if?: WorkflowIfNode;
  loop?: WorkflowLoopNode;
}

export interface WorkflowEdge {
  from_node_id: string;
  to_node_id: string;
}

export interface WorkflowDefinition {
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
}

export interface AgentMessageTaskCreateRequest {
  message: string;
  session_id?: string;
  runtime_overrides?: TaskRuntimeOverrides;
  task_kind?: 'agent_message';
  interval_seconds?: number;
  cron_expr?: string;
  trace_id?: string;
}

export interface TaskRuntimeOverrides {
  model?: string;
  tool_allowlist?: string[];
}

export interface WorkflowToolNode {
  tool_name: string;
  arguments?: Record<string, unknown>;
}

export interface WorkflowLLMNode {
  prompt: string;
  system_prompt?: string;
}

export interface WorkflowAgentNode {
  message: string;
}

export interface WorkflowIfNode {
  source_node_id?: string;
  operator: 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'is_empty' | 'not_empty';
  value?: string;
  true_node_id: string;
  false_node_id: string;
}

export interface WorkflowTaskCreateRequest {
  task_kind: 'workflow';
  workflow: WorkflowDefinition;
  interval_seconds?: number;
  cron_expr?: string;
  trace_id?: string;
}

export interface WorkflowLoopNode {
  max_iterations: number;
  body_node_id: string;
  exit_node_id: string;
}

export interface TaskUpdateRequest {
  id: string;
  message?: string;
  session_id?: string;
  runtime_overrides?: TaskRuntimeOverrides;
  task_kind?: 'agent_message' | 'workflow';
  workflow?: WorkflowDefinition;
  interval_seconds?: number;
  cron_expr?: string;
  enabled?: boolean;
  trace_id?: string;
}

export interface AgentMessageTaskPayload {
  id: string;
  message: string;
  session_id?: string;
  runtime_overrides?: TaskRuntimeOverrides;
  task_kind: 'agent_message';
  schedule_type: 'interval' | 'cron';
  interval_seconds?: number;
  cron_expr?: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  last_run_at?: string;
  next_run_at?: string;
  last_error?: string;
}

export interface WorkflowTaskPayload {
  id: string;
  task_kind: 'workflow';
  workflow: WorkflowDefinition;
  schedule_type: 'interval' | 'cron';
  interval_seconds?: number;
  cron_expr?: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  last_run_at?: string;
  next_run_at?: string;
  last_error?: string;
}

export interface WorkflowStartNode {
  inputs?: WorkflowInputVariable[];
}

export interface WorkflowInputVariable {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array';
  required?: boolean;
  default?: unknown;
  description?: string;
}

export type AgentSendResponse = AgentSendSuccessResponse | AgentSendAwaitingHumanResponse;

export type TaskCreateRequest = AgentMessageTaskCreateRequest | WorkflowTaskCreateRequest;

export type TaskPayload = AgentMessageTaskPayload | WorkflowTaskPayload;
