// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package orchestration

import "encoding/json"

const (
	busActionAgentSend = "AGENT_SEND"
	busActionAgentStop = "AGENT_STOP"
	busActionHumanResponse = "HUMAN_RESPONSE"
	busActionConfigGet = "CONFIG_GET"
	busActionConfigUpdate = "CONFIG_UPDATE"
	busActionTaskCreate = "TASK_CREATE"
	busActionTaskList = "TASK_LIST"
	busActionTaskGet = "TASK_GET"
	busActionTaskUpdate = "TASK_UPDATE"
	busActionTaskRunNow = "TASK_RUN_NOW"
	busActionTaskLogs = "TASK_LOGS"
	busActionTaskDelete = "TASK_DELETE"
	busActionRssInboxPoll = "RSS_INBOX_POLL"
	busActionRssInboxList = "RSS_INBOX_LIST"
	busActionRssInboxGet = "RSS_INBOX_GET"
	busActionRssInboxGroups = "RSS_INBOX_GROUPS"
	busActionRssBriefingBuild = "RSS_BRIEFING_BUILD"
	busActionRssBriefingGet = "RSS_BRIEFING_GET"
)

const (
	busStatusSuccess = "success"
	busStatusError = "error"
)

const busAssistantSessionEndSignal = "END_SESSION"

// assistantSessionEndSignalPayload 对齐 core/shared/schema.json 的 assistantSessionEndSignal。
type assistantSessionEndSignalPayload struct {
	Signal string `json:"signal"`
	Message string `json:"message"`
}

// agentRequest 对齐 core/shared/schema.json 的 agentRequest。
type agentRequest struct {
	Mode string `json:"mode,omitempty"`
	Message string `json:"message,omitempty"`
	Images []sessionImageContent `json:"images,omitempty"`
	SessionID string `json:"session_id,omitempty"`
	ProjectRoot string `json:"project_root,omitempty"`
	TraceID string `json:"trace_id,omitempty"`
}

// agentIterationSummaryItem 对齐 core/shared/schema.json 的 agentIterationSummaryItem。
type agentIterationSummaryItem struct {
	Iteration int `json:"iteration"`
	Did string `json:"did"`
	Remaining string `json:"remaining"`
	Completed bool `json:"completed,omitempty"`
	TraceID string `json:"trace_id,omitempty"`
	RecordedAt string `json:"recorded_at,omitempty"`
	FinalChangeLog string `json:"final_change_log,omitempty"`
}

// askHumanOption 对齐 core/shared/schema.json 的 askHumanOption。
type askHumanOption struct {
	Label string `json:"label"`
	AllowCustom bool `json:"allow_custom,omitempty"`
}

// agentResponse 对齐 core/shared/schema.json 的 agentResponsePayload。
type agentResponse struct {
	Message string `json:"message"`
	SessionID string `json:"session_id"`
	SessionEnded bool `json:"session_ended"`
	Mode string `json:"mode,omitempty"`
	IterationCount int `json:"iteration_count,omitempty"`
	StoppedBy string `json:"stopped_by,omitempty"`
	FinalChangeLog string `json:"final_change_log,omitempty"`
	IterationSummary []agentIterationSummaryItem `json:"iteration_summary,omitempty"`
	SessionEnd *assistantSessionEndSignalPayload `json:"session_end,omitempty"`
}

// askHumanAwaitingResponse 对齐 core/shared/schema.json 的 agentAwaitingHumanPayload。
type askHumanAwaitingResponse struct {
	Status string `json:"status"`
	SessionID string `json:"session_id"`
	QuestionID string `json:"question_id"`
	Prompt string `json:"prompt"`
	SelectionMode string `json:"selection_mode,omitempty"`
	Options []askHumanOption `json:"options,omitempty"`
}

// agentStopResponse 对齐 core/shared/schema.json 的 agentStopResponsePayload。
type agentStopResponse struct {
	Status string `json:"status"`
	Message string `json:"message"`
	SessionID string `json:"session_id,omitempty"`
}

// humanResponseParams 对齐 core/shared/schema.json 的 humanResponseRequest。
type humanResponseParams struct {
	SessionID string `json:"session_id"`
	QuestionID string `json:"question_id"`
	Answer string `json:"answer"`
	Cancelled bool `json:"cancelled,omitempty"`
}

// humanResponseAck 对齐 core/shared/schema.json 的 humanResponseAck。
type humanResponseAck struct {
	SessionID string `json:"session_id"`
	QuestionID string `json:"question_id"`
	Accepted bool `json:"accepted"`
}

// agentStreamEventContract 对齐 core/shared/schema.json 的 agentStreamEvent。
type agentStreamEventContract struct {
	ID string `json:"id"`
	StepID string `json:"step_id"`
	TraceID string `json:"trace_id"`
	SessionID string `json:"session_id,omitempty"`
	Turn int `json:"turn"`
	Type string `json:"type"`
	Payload map[string]any `json:"payload"`
	At string `json:"at,omitempty"`
}

// sessionImageContent 对齐 core/shared/schema.json 的 sessionImageContent。
type sessionImageContent struct {
	Path string `json:"path,omitempty"`
	URL string `json:"url,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
	Width int `json:"width,omitempty"`
	Height int `json:"height,omitempty"`
	SHA256 string `json:"sha256,omitempty"`
	Bytes int `json:"bytes,omitempty"`
}

// sessionFileContent 对齐 core/shared/schema.json 的 sessionFileContent。
type sessionFileContent struct {
	ArtifactID string `json:"artifact_id"`
	Name string `json:"name"`
	MimeType string `json:"mime_type,omitempty"`
	Bytes int `json:"bytes,omitempty"`
	SHA256 string `json:"sha256,omitempty"`
	DownloadURL string `json:"download_url"`
	SourcePath string `json:"source_path,omitempty"`
	Note string `json:"note,omitempty"`
}

// sessionPushEventContract 对齐 core/shared/schema.json 的 sessionPushEvent。
type sessionPushEventContract struct {
	ID string `json:"id"`
	Type string `json:"type"`
	TraceID string `json:"trace_id,omitempty"`
	SessionID string `json:"session_id"`
	Payload map[string]any `json:"payload"`
	At string `json:"at,omitempty"`
}

// agentRunStartedPayload 对齐 core/shared/schema.json 的 agentRunStartedPayload。
type agentRunStartedPayload struct {
	SessionID string `json:"session_id,omitempty"`
}

// sessionContentPart 对齐 core/shared/schema.json 的 sessionContentPart。
type sessionContentPart struct {
	Type string `json:"type"`
	Text string `json:"text,omitempty"`
	Image *sessionImageContent `json:"image,omitempty"`
	File *sessionFileContent `json:"file,omitempty"`
}

// agentCompletionDeltaPayload 对齐 core/shared/schema.json 的 agentCompletionDeltaPayload。
type agentCompletionDeltaPayload struct {
	Kind string `json:"kind"`
	Text string `json:"text,omitempty"`
	Thinking string `json:"thinking,omitempty"`
	ToolCallIndex int `json:"tool_call_index,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	ToolName string `json:"tool_name,omitempty"`
	ArgumentsFragment string `json:"arguments_fragment,omitempty"`
}

// sessionToolCall 对齐 core/shared/schema.json 的 sessionToolCall。
type sessionToolCall struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Arguments map[string]any `json:"arguments"`
}

// agentToolCallStartedPayload 对齐 core/shared/schema.json 的 agentToolCallStartedPayload。
type agentToolCallStartedPayload struct {
	Tool string `json:"tool,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	ArgumentsJson string `json:"arguments_json,omitempty"`
}

// sessionToolResult 对齐 core/shared/schema.json 的 sessionToolResult。
type sessionToolResult struct {
	Status string `json:"status"`
	Tool string `json:"tool"`
	TraceID string `json:"trace_id,omitempty"`
	Output string `json:"output,omitempty"`
	Error string `json:"error,omitempty"`
}

// agentToolCallFinishedPayload 对齐 core/shared/schema.json 的 agentToolCallFinishedPayload。
type agentToolCallFinishedPayload struct {
	Tool string `json:"tool,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	Status string `json:"status,omitempty"`
	Error string `json:"error,omitempty"`
	Output string `json:"output,omitempty"`
}

// sessionHumanInteraction 对齐 core/shared/schema.json 的 sessionHumanInteraction。
type sessionHumanInteraction struct {
	QuestionID string `json:"question_id"`
	Prompt string `json:"prompt"`
	SelectionMode string `json:"selection_mode,omitempty"`
	Options []askHumanOption `json:"options,omitempty"`
	Answer string `json:"answer,omitempty"`
}

// agentStreamMessagePayload 对齐 core/shared/schema.json 的 agentStreamMessagePayload。
type agentStreamMessagePayload struct {
	Text string `json:"text"`
	SessionID string `json:"session_id,omitempty"`
}

// sessionMessage 对齐 core/shared/schema.json 的 sessionMessage。
type sessionMessage struct {
	Index int `json:"index"`
	Role string `json:"role"`
	Text string `json:"text,omitempty"`
	Content []sessionContentPart `json:"content,omitempty"`
	ToolCalls []sessionToolCall `json:"tool_calls,omitempty"`
	ToolResult *sessionToolResult `json:"tool_result,omitempty"`
	HumanInteraction *sessionHumanInteraction `json:"human_interaction,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	InProgress bool `json:"in_progress,omitempty"`
	Thinking string `json:"thinking,omitempty"`
}

// agentDonePayload 对齐 core/shared/schema.json 的 agentDonePayload。
type agentDonePayload struct {
	SessionID string `json:"session_id,omitempty"`
	SessionEnded bool `json:"session_ended,omitempty"`
}

// sessionMetadata 对齐 core/shared/schema.json 的 sessionMetadata。
type sessionMetadata struct {
	ID string `json:"id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	MessageCount int `json:"message_count"`
	TokenCount int `json:"token_count"`
}

// sessionSidebarPartition 对齐 core/shared/schema.json 的 sessionSidebarPartition。
type sessionSidebarPartition struct {
	ID string `json:"id"`
	Name string `json:"name"`
}

// sessionSidebarPartitionState 对齐 core/shared/schema.json 的 sessionSidebarPartitionState。
type sessionSidebarPartitionState struct {
	Version int `json:"version"`
	Partitions []sessionSidebarPartition `json:"partitions"`
	Assignments map[string]string `json:"assignments"`
}

// sessionSidebarPartitionPutRequest 对齐 core/shared/schema.json 的 sessionSidebarPartitionPutRequest。
type sessionSidebarPartitionPutRequest struct {
	Version int `json:"version"`
	Partitions []sessionSidebarPartition `json:"partitions"`
	Assignments map[string]string `json:"assignments"`
	TraceID string `json:"trace_id,omitempty"`
}

// sessionMessagePage 对齐 core/shared/schema.json 的 sessionMessagePage。
type sessionMessagePage struct {
	Limit int `json:"limit"`
	Before *int `json:"before,omitempty"`
	StartIndex *int `json:"start_index,omitempty"`
	EndIndex *int `json:"end_index,omitempty"`
	HasMoreBefore bool `json:"has_more_before"`
	NextBefore *int `json:"next_before,omitempty"`
}

// sessionTurnDraftSegment 对齐 core/shared/schema.json 的 sessionTurnDraftSegment。
type sessionTurnDraftSegment struct {
	ID string `json:"id"`
	Content string `json:"content"`
}

// sessionTurnDraftTool 对齐 core/shared/schema.json 的 sessionTurnDraftTool。
type sessionTurnDraftTool struct {
	ID string `json:"id"`
	Content string `json:"content"`
	ToolInput string `json:"tool_input,omitempty"`
	ToolName string `json:"tool_name,omitempty"`
	ToolStatus string `json:"tool_status,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	TraceID string `json:"trace_id,omitempty"`
}

// sessionTurnDraft 对齐 core/shared/schema.json 的 sessionTurnDraft。
type sessionTurnDraft struct {
	TraceID string `json:"trace_id"`
	Turn int `json:"turn"`
	AssistantSegments []sessionTurnDraftSegment `json:"assistant_segments"`
	ThinkingSegments []sessionTurnDraftSegment `json:"thinking_segments"`
	Tools []sessionTurnDraftTool `json:"tools"`
	ItemOrder []string `json:"item_order"`
}

// agentErrorPayload 对齐 core/shared/schema.json 的 agentErrorPayload。
type agentErrorPayload struct {
	Message string `json:"message"`
	SessionID string `json:"session_id,omitempty"`
	Code int `json:"code,omitempty"`
}

// sessionDetail 对齐 core/shared/schema.json 的 sessionDetail。
type sessionDetail struct {
	ID string `json:"id"`
	Messages []sessionMessage `json:"messages"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	MessageCount int `json:"message_count"`
	Page sessionMessagePage `json:"page"`
	TokenCount int `json:"token_count"`
	TurnDraft *sessionTurnDraft `json:"turn_draft,omitempty"`
}

// configResponse 对齐 core/shared/schema.json 的 bridgeConfig。
type configResponse struct {
	Provider string `json:"provider"`
	ProviderType string `json:"provider_type"`
	BaseURL string `json:"base_url"`
	Model string `json:"model"`
	ChatPath string `json:"chat_path"`
	ProjectRoot string `json:"project_root"`
	MaxTurns int `json:"max_turns"`
	LlmCompletionRetryCount int `json:"llm_completion_retry_count"`
	LlmCompletionRetryIntervalMs int `json:"llm_completion_retry_interval_ms"`
	APIKeySet bool `json:"api_key_set"`
	ModelSelectionEnabled bool `json:"model_selection_enabled"`
	SessionHumanLogFullEnabled bool `json:"session_human_log_full_enabled"`
	SessionSystemPromptVisibleEnabled bool `json:"session_system_prompt_visible_enabled"`
	AssistantMarkdownEnabled bool `json:"assistant_markdown_enabled"`
	ToolCallCompactOutputEnabled bool `json:"tool_call_compact_output_enabled"`
	MemoryModeEnabled bool `json:"memory_mode_enabled"`
	MicrocompactEnabled bool `json:"microcompact_enabled"`
	WebSearchTavilyURL string `json:"web_search_tavily_url"`
	WebSearchExaURL string `json:"web_search_exa_url"`
	WebSearchTavilyAPIKeySet bool `json:"web_search_tavily_api_key_set"`
	WebSearchExaAPIKeySet bool `json:"web_search_exa_api_key_set"`
}

// assistantMessagePushPayload 对齐 core/shared/schema.json 的 sessionPushAssistantMessagePayload。
type assistantMessagePushPayload struct {
	Message string `json:"message"`
	SessionEnded bool `json:"session_ended"`
	SessionEnd *assistantSessionEndSignalPayload `json:"session_end,omitempty"`
}

// configUpdateRequest 对齐 core/shared/schema.json 的 configUpdate。
type configUpdateRequest struct {
	Provider *string `json:"provider,omitempty"`
	APIKey *string `json:"api_key,omitempty"`
	BaseURL *string `json:"base_url,omitempty"`
	Model *string `json:"model,omitempty"`
	ChatPath *string `json:"chat_path,omitempty"`
	ProjectRoot *string `json:"project_root,omitempty"`
	MaxTurns *int `json:"max_turns,omitempty"`
	LlmCompletionRetryCount *int `json:"llm_completion_retry_count,omitempty"`
	LlmCompletionRetryIntervalMs *int `json:"llm_completion_retry_interval_ms,omitempty"`
	SessionHumanLogFullEnabled *bool `json:"session_human_log_full_enabled,omitempty"`
	SessionSystemPromptVisibleEnabled *bool `json:"session_system_prompt_visible_enabled,omitempty"`
	AssistantMarkdownEnabled *bool `json:"assistant_markdown_enabled,omitempty"`
	ToolCallCompactOutputEnabled *bool `json:"tool_call_compact_output_enabled,omitempty"`
	MemoryModeEnabled *bool `json:"memory_mode_enabled,omitempty"`
	MicrocompactEnabled *bool `json:"microcompact_enabled,omitempty"`
	WebSearchTavilyURL *string `json:"web_search_tavily_url,omitempty"`
	WebSearchExaURL *string `json:"web_search_exa_url,omitempty"`
	WebSearchTavilyAPIKey *string `json:"web_search_tavily_api_key,omitempty"`
	WebSearchExaAPIKey *string `json:"web_search_exa_api_key,omitempty"`
	TraceID string `json:"trace_id,omitempty"`
}

// awaitingHumanPushPayload 对齐 core/shared/schema.json 的 sessionPushAwaitingHumanPayload。
type awaitingHumanPushPayload struct {
	QuestionID string `json:"question_id"`
	Prompt string `json:"prompt"`
	SelectionMode string `json:"selection_mode,omitempty"`
	Options []askHumanOption `json:"options,omitempty"`
}

// providerConfigResponse 对齐 core/shared/schema.json 的 providerConfig。
type providerConfigResponse struct {
	Name string `json:"name"`
	Type string `json:"type"`
	BaseURL string `json:"base_url"`
	Models []string `json:"models,omitempty"`
	ContextWindowTokens int `json:"context_window_tokens,omitempty"`
	ResponseReserveTokens int `json:"response_reserve_tokens,omitempty"`
	ModelContextWindowTokens map[string]int `json:"model_context_window_tokens,omitempty"`
	ModelResponseReserveTokens map[string]int `json:"model_response_reserve_tokens,omitempty"`
	APIKeySet bool `json:"api_key_set"`
}

// providerConfigInput 对齐 core/shared/schema.json 的 providerConfigInput。
type providerConfigInput struct {
	Name string `json:"name"`
	Type string `json:"type"`
	BaseURL *string `json:"base_url,omitempty"`
	APIKey *string `json:"api_key,omitempty"`
	Models []string `json:"models,omitempty"`
	ContextWindowTokens int `json:"context_window_tokens,omitempty"`
	ResponseReserveTokens int `json:"response_reserve_tokens,omitempty"`
	ModelContextWindowTokens map[string]int `json:"model_context_window_tokens,omitempty"`
	ModelResponseReserveTokens map[string]int `json:"model_response_reserve_tokens,omitempty"`
	TraceID string `json:"trace_id,omitempty"`
}

// providerListResponse 对齐 core/shared/schema.json 的 providerListResponse。
type providerListResponse struct {
	Providers []providerConfigResponse `json:"providers"`
	ActiveProvider string `json:"active_provider"`
}

// setActiveProviderRequest 对齐 core/shared/schema.json 的 setActiveProviderRequest。
type setActiveProviderRequest struct {
	Name string `json:"name"`
	TraceID string `json:"trace_id,omitempty"`
}

// workflowNodeContract 对齐 core/shared/schema.json 的 workflowNode。
type workflowNodeContract struct {
	ID string `json:"id"`
	Type string `json:"type"`
	Start workflowStartNodeContract `json:"start,omitempty"`
	Tool workflowToolNodeContract `json:"tool,omitempty"`
	Llm workflowLLMNodeContract `json:"llm,omitempty"`
	Agent workflowAgentNodeContract `json:"agent,omitempty"`
	If workflowIfNodeContract `json:"if,omitempty"`
	Loop workflowLoopNodeContract `json:"loop,omitempty"`
}

// workflowEdgeContract 对齐 core/shared/schema.json 的 workflowEdge。
type workflowEdgeContract struct {
	FromNodeID string `json:"from_node_id"`
	ToNodeID string `json:"to_node_id"`
}

// workflowDefinitionContract 对齐 core/shared/schema.json 的 workflowDefinition。
type workflowDefinitionContract struct {
	Nodes []workflowNodeContract `json:"nodes"`
	Edges []workflowEdgeContract `json:"edges"`
}

// taskRuntimeOverridesContract 对齐 core/shared/schema.json 的 taskRuntimeOverrides。
type taskRuntimeOverridesContract struct {
	ProviderName string `json:"provider_name,omitempty"`
	Model string `json:"model,omitempty"`
	SystemPrompt string `json:"system_prompt,omitempty"`
	ToolAllowlist []string `json:"tool_allowlist,omitempty"`
	ToolAllowlistOnly *bool `json:"tool_allowlist_only,omitempty"`
	MaxTurns *int `json:"max_turns,omitempty"`
}

// workflowToolNodeContract 对齐 core/shared/schema.json 的 workflowToolNode。
type workflowToolNodeContract struct {
	ToolName string `json:"tool_name"`
	Arguments map[string]any `json:"arguments,omitempty"`
}

// workflowLLMNodeContract 对齐 core/shared/schema.json 的 workflowLLMNode。
type workflowLLMNodeContract struct {
	Prompt string `json:"prompt"`
	SystemPrompt string `json:"system_prompt,omitempty"`
}

// workflowAgentNodeContract 对齐 core/shared/schema.json 的 workflowAgentNode。
type workflowAgentNodeContract struct {
	Message string `json:"message"`
	RuntimeOverrides taskRuntimeOverridesContract `json:"runtime_overrides,omitempty"`
}

// workflowIfNodeContract 对齐 core/shared/schema.json 的 workflowIfNode。
type workflowIfNodeContract struct {
	SourceNodeID string `json:"source_node_id,omitempty"`
	Operator string `json:"operator"`
	Value string `json:"value,omitempty"`
	TrueNodeID string `json:"true_node_id"`
	FalseNodeID string `json:"false_node_id"`
}

// workflowLoopNodeContract 对齐 core/shared/schema.json 的 workflowLoopNode。
type workflowLoopNodeContract struct {
	MaxIterations int `json:"max_iterations"`
	BodyNodeID string `json:"body_node_id"`
	ExitNodeID string `json:"exit_node_id"`
}

// workflowStartNodeContract 对齐 core/shared/schema.json 的 workflowStartNode。
type workflowStartNodeContract struct {
	Inputs []workflowInputVariableContract `json:"inputs,omitempty"`
}

// workflowInputVariableContract 对齐 core/shared/schema.json 的 workflowInputVariable。
type workflowInputVariableContract struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Required bool `json:"required,omitempty"`
	Default any `json:"default,omitempty"`
	Description string `json:"description,omitempty"`
}

// apiRequest 对齐 core/shared/schema.json 的 requestEnvelope。
type apiRequest struct {
	Action    string          `json:"action"`
	Params    json.RawMessage `json:"params"`
	TraceID   string          `json:"trace_id"`
	RequestID string          `json:"request_id,omitempty"`
}

// apiResponse 对齐 core/shared/schema.json 的 responseEnvelope。
type apiResponse struct {
	Status    string `json:"status"`
	Payload   any    `json:"payload"`
	Error     string `json:"error"`
	RequestID string `json:"request_id,omitempty"`
}
