from __future__ import annotations

from contract_codegen.catalog import collect_definitions, dereference_schema, target_name_map
from contract_codegen.common import (
    non_null_one_of_candidates,
    object_additional_properties_schema,
    object_has_declared_properties,
    object_is_open,
    schema_ref_name,
)

GO_INITIALISMS = {
    "api": "API",
    "id": "ID",
    "url": "URL",
    "sha256": "SHA256",
}


def go_field_name(name: str) -> str:
    rendered: list[str] = []
    for part in name.split("_"):
        lower = part.lower()
        if lower in GO_INITIALISMS:
            rendered.append(GO_INITIALISMS[lower])
            continue
        rendered.append(part[:1].upper() + part[1:])
    return "".join(rendered)


def _object_type(schema: dict, target_names: dict[str, str], prop_schema: dict) -> str:
    if object_has_declared_properties(prop_schema):
        raise ValueError(f"inline structured Go object must be promoted to $defs: {prop_schema}")

    additional = object_additional_properties_schema(prop_schema)
    if additional is not None:
        return f'map[string]{_type_for_schema(schema, target_names, additional)}'
    if object_is_open(prop_schema):
        return "map[string]any"
    raise ValueError(f"unsupported closed Go object schema: {prop_schema}")


def _inner_type(schema: dict, target_names: dict[str, str], prop_schema: dict) -> str:
    if not prop_schema:
        return "any"

    ref_value = prop_schema.get("$ref")
    if ref_value:
        ref_name = schema_ref_name(ref_value)
        if ref_name in target_names:
            return target_names[ref_name]
        return _inner_type(schema, target_names, dereference_schema(schema, prop_schema))

    schema_type = prop_schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float64"
    if schema_type == "array":
        item_schema = prop_schema.get("items", {})
        return f'[]{_inner_type(schema, target_names, item_schema)}'
    if schema_type == "object":
        return _object_type(schema, target_names, prop_schema)
    raise ValueError(f"unsupported Go schema: {prop_schema}")


def _type_for_schema(schema: dict, target_names: dict[str, str], prop_schema: dict) -> str:
    if prop_schema.get("oneOf"):
        non_null = non_null_one_of_candidates(prop_schema)
        if len(non_null) != 1:
            raise ValueError(f"unsupported Go oneOf schema: {prop_schema}")
        inner = _inner_type(schema, target_names, non_null[0])
        return inner if inner.startswith("*") else f"*{inner}"

    inner = _inner_type(schema, target_names, prop_schema)
    if prop_schema.get("x-go-pointer") and inner in {"string", "bool", "int"}:
        return f"*{inner}"
    return inner


def _render_object(schema: dict, spec, target_names: dict[str, str]) -> str:
    required = set(spec.definition.get("required", []))
    lines = [
        f"// {spec.target_name} 对齐 core/shared/schema.json 的 {spec.name}。",
        f"type {spec.target_name} struct {{",
    ]
    for prop_name, prop_schema in spec.definition.get("properties", {}).items():
        tag_suffix = "" if prop_name in required else ",omitempty"
        field_type = _type_for_schema(schema, target_names, prop_schema)
        lines.append(f'\t{go_field_name(prop_name)} {field_type} `json:"{prop_name}{tag_suffix}"`')
    lines.append("}")
    return "\n".join(lines)


def _render_actions(actions: list[str]) -> str:
    return "\n".join(f'\tbusAction{action.title().replace("_", "")} = "{action}"' for action in actions)


def _render_statuses(statuses: list[str]) -> str:
    return "\n".join(f'\tbusStatus{status.title()} = "{status}"' for status in statuses)


def render(schema: dict, package_name: str) -> str:
    target_names = target_name_map(schema, "go")
    actions = schema["$defs"]["action"]["enum"]
    statuses = schema["$defs"]["status"]["enum"]
    signal = schema["$defs"]["assistantSessionEndSignal"]["properties"]["signal"]["const"]
    objects = "\n\n".join(
        _render_object(schema, spec, target_names) for spec in collect_definitions(schema, "go", kind="object")
    )

    return f'''// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json ({schema.get("$id", "")})

package {package_name}

import "encoding/json"

const (
{_render_actions(actions)}
)

const (
{_render_statuses(statuses)}
)

const busAssistantSessionEndSignal = "{signal}"

{objects}

// apiRequest 对齐 core/shared/schema.json 的 requestEnvelope。
type apiRequest struct {{
\tAction    string          `json:"action"`
\tParams    json.RawMessage `json:"params"`
\tTraceID   string          `json:"trace_id"`
\tRequestID string          `json:"request_id,omitempty"`
}}

// apiResponse 对齐 core/shared/schema.json 的 responseEnvelope。
type apiResponse struct {{
\tStatus    string `json:"status"`
\tPayload   any    `json:"payload"`
\tError     string `json:"error"`
\tRequestID string `json:"request_id,omitempty"`
}}
'''
