from __future__ import annotations

from contract_codegen.catalog import collect_definitions, dereference_schema, kotlin_union_implementers, target_name_map
from contract_codegen.common import (
    non_null_one_of_candidates,
    object_additional_properties_schema,
    object_has_declared_properties,
    object_is_open,
    schema_ref_name,
)


def _field_name(name: str) -> str:
    head, *tail = name.split("_")
    return head[:1].lower() + head[1:] + "".join(part[:1].upper() + part[1:] for part in tail)


def _object_type(schema: dict, target_names: dict[str, str], prop_schema: dict) -> str:
    if object_has_declared_properties(prop_schema):
        raise ValueError(f"inline structured Kotlin object must be promoted to $defs: {prop_schema}")

    additional = object_additional_properties_schema(prop_schema)
    if additional is not None:
        return f"Map<String, {_type_for_schema(schema, target_names, additional, required=True)}>"
    if object_is_open(prop_schema):
        return "JsonObject"
    raise ValueError(f"unsupported closed Kotlin object schema: {prop_schema}")


def _inner_type(schema: dict, target_names: dict[str, str], prop_schema: dict) -> str:
    if not prop_schema:
        return "JsonElement"

    ref_value = prop_schema.get("$ref")
    if ref_value:
        ref_name = schema_ref_name(ref_value)
        if ref_name in target_names:
            return target_names[ref_name]
        return _inner_type(schema, target_names, dereference_schema(schema, prop_schema))

    schema_type = prop_schema.get("type")
    if schema_type == "string":
        return "String"
    if schema_type == "boolean":
        return "Boolean"
    if schema_type == "integer":
        return "Int"
    if schema_type == "number":
        return "Double"
    if schema_type == "array":
        inner = _type_for_schema(schema, target_names, prop_schema.get("items", {}), required=True)
        return f"List<{inner}>"
    if schema_type == "object":
        return _object_type(schema, target_names, prop_schema)
    raise ValueError(f"unsupported Kotlin schema: {prop_schema}")


def _type_for_schema(schema: dict, target_names: dict[str, str], prop_schema: dict, *, required: bool) -> str:
    if prop_schema.get("oneOf"):
        non_null = non_null_one_of_candidates(prop_schema)
        if len(non_null) != 1:
            raise ValueError(f"unsupported Kotlin oneOf schema: {prop_schema}")
        return f'{_inner_type(schema, target_names, non_null[0])}?'

    inner = _inner_type(schema, target_names, prop_schema)
    return inner if required else f"{inner}?"


def _render_object(schema: dict, spec, target_names: dict[str, str], implementers: dict[str, list[str]]) -> str:
    required = set(spec.definition.get("required", []))
    properties = list(spec.definition.get("properties", {}).items())
    lines = ["@Serializable", f"data class {spec.target_name}("]
    for index, (prop_name, prop_schema) in enumerate(properties):
        field_name = _field_name(prop_name)
        if field_name != prop_name:
            lines.append(f'    @SerialName("{prop_name}")')
        field_type = _type_for_schema(schema, target_names, prop_schema, required=prop_name in required)
        default = "" if prop_name in required else " = null"
        suffix = "," if index < len(properties) - 1 else ""
        lines.append(f"    val {field_name}: {field_type}{default}{suffix}")
    union_names = implementers.get(spec.name, [])
    impl_suffix = f" : {', '.join(union_names)}" if union_names else ""
    lines.append(f"){impl_suffix}")
    return "\n".join(lines)


def _render_union(spec) -> str:
    if spec.target_config.get("kind") != "sealed_interface":
        raise ValueError(f"unsupported Kotlin union config for {spec.name}")
    return f"sealed interface {spec.target_name}"


def render(schema: dict) -> str:
    target_names = target_name_map(schema, "kotlin")
    implementers = kotlin_union_implementers(schema)
    unions = "\n\n".join(_render_union(spec) for spec in collect_definitions(schema, "kotlin", kind="union"))
    objects = "\n\n".join(
        _render_object(schema, spec, target_names, implementers)
        for spec in collect_definitions(schema, "kotlin", kind="object")
    )

    return f'''// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json ({schema.get("$id", "")})

package dev.ghostos.android.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

@Serializable
data class ApiRequest<TParams>(
    val action: String,
    val params: TParams,
    @SerialName("trace_id") val traceId: String,
    @SerialName("request_id") val requestId: String? = null
)

@Serializable
data class ApiEnvelope<TPayload>(
    val status: String,
    val payload: TPayload? = null,
    val error: String = ""
)

{unions}

{objects}
'''
