// Code generated by go generate; DO NOT EDIT.

package context

const defaultPromptConfigYAML = "# Ghost-OS 系统提示词配置\nversion: \"1.0\"\n\nsystem:\n  default: |\n    Role: {{rule}}\n\n    Job:\n    {{core_job}}\n\n    Skills:\n    {{skills_catalog}}\n\n    Skill Context:\n    {{dynamic_skill_context}}\n\n    Context:\n    {{context}}\n\n  rule: |\n    Ghost-OS bridge agent (digital twin execution layer).\n\n  core_job: |\n    Coordinate local execution, web retrieval, desktop interaction, and human confirmation.\n"
