// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package app

import "encoding/json"

const (
	busActionPing                  = "PING"
	busActionAgentSend             = "AGENT_SEND"
	busActionAgentStop             = "AGENT_STOP"
	busActionHumanResponse         = "HUMAN_RESPONSE"
	busActionConfigGet             = "CONFIG_GET"
	busActionConfigUpdate          = "CONFIG_UPDATE"
	busActionMemoryQuery           = "MEMORY_QUERY"
	busActionMemoryArchive         = "MEMORY_ARCHIVE"
	busActionMemoryDecisionQuery   = "MEMORY_DECISION_QUERY"
	busActionMemoryDecisionStats   = "MEMORY_DECISION_STATS"
	busActionMemoryDecisionRebuild = "MEMORY_DECISION_REBUILD"
	busActionListFiles             = "LIST_FILES"
	busActionReadFile              = "READ_FILE"
	busActionSearchFiles           = "SEARCH_FILES"
	busActionApplyDiff             = "APPLY_DIFF"
	busActionBashExec              = "BASH_EXEC"
	busActionScriptExec            = "SCRIPT_EXEC"
	busActionScreenShot            = "SCREEN_SHOT"
	busActionMouseClick            = "MOUSE_CLICK"
	busActionBrowserQuery          = "BROWSER_QUERY"
)

const (
	busStatusSuccess = "success"
	busStatusError   = "error"
)

const busAssistantSessionEndSignal = "END_SESSION"

// assistantSessionEndSignalPayload 对齐 core/shared/schema.json 的 assistantSessionEndSignal。
type assistantSessionEndSignalPayload struct {
	Signal  string `json:"signal"`
	Message string `json:"message"`
}

// agentRequest 对齐 core/shared/schema.json 的 agentRequest。
type agentRequest struct {
	Message   string `json:"message"`
	SessionID string `json:"session_id,omitempty"`
	TraceID   string `json:"trace_id,omitempty"`
}

// agentResponse 对齐 core/shared/schema.json 的 agentResponsePayload。
type agentResponse struct {
	Message      string                            `json:"message"`
	SessionID    string                            `json:"session_id"`
	SessionEnded bool                              `json:"session_ended"`
	SessionEnd   *assistantSessionEndSignalPayload `json:"session_end,omitempty"`
}

// askHumanAwaitingResponse 对齐 core/shared/schema.json 的 agentAwaitingHumanPayload。
type askHumanAwaitingResponse struct {
	Status     string `json:"status"`
	SessionID  string `json:"session_id"`
	QuestionID string `json:"question_id"`
	Prompt     string `json:"prompt"`
}

// agentStopResponse 对齐 core/shared/schema.json 的 agentStopResponsePayload。
type agentStopResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

// humanResponseParams 对齐 core/shared/schema.json 的 humanResponseRequest。
type humanResponseParams struct {
	SessionID  string `json:"session_id"`
	QuestionID string `json:"question_id"`
	Answer     string `json:"answer"`
}

// humanResponseAck 对齐 core/shared/schema.json 的 humanResponseAck。
type humanResponseAck struct {
	SessionID  string `json:"session_id"`
	QuestionID string `json:"question_id"`
	Accepted   bool   `json:"accepted"`
}

// memoryDecisionQueryRequest 对齐 core/shared/schema.json 的 memoryDecisionQueryRequest。
type memoryDecisionQueryRequest struct {
	Namespace         string         `json:"namespace,omitempty"`
	TimeRange         map[string]any `json:"time_range,omitempty"`
	Limit             int            `json:"limit,omitempty"`
	SemanticQuery     string         `json:"semantic_query,omitempty"`
	Keywords          []string       `json:"keywords,omitempty"`
	DecisionTypes     []string       `json:"decision_types,omitempty"`
	DecisionReuseOnly bool           `json:"decision_reuse_only,omitempty"`
	EnvironmentStrict bool           `json:"environment_strict,omitempty"`
	MinReuseScore     float64        `json:"min_reuse_score,omitempty"`
}

// memoryDecisionStatsRequest 对齐 core/shared/schema.json 的 memoryDecisionStatsRequest。
type memoryDecisionStatsRequest struct {
	Namespace string `json:"namespace,omitempty"`
}

// memoryDecisionRebuildRequest 对齐 core/shared/schema.json 的 memoryDecisionRebuildRequest。
type memoryDecisionRebuildRequest struct {
	Namespace      string         `json:"namespace,omitempty"`
	TimeRange      map[string]any `json:"time_range,omitempty"`
	MaxSessions    int            `json:"max_sessions,omitempty"`
	DryRun         bool           `json:"dry_run,omitempty"`
	IncludeRecipes bool           `json:"include_recipes,omitempty"`
	RebuildMemos   bool           `json:"rebuild_memos,omitempty"`
	ResetNamespace bool           `json:"reset_namespace,omitempty"`
}

// memoryDecisionQueryPayload 对齐 core/shared/schema.json 的 memoryDecisionQueryPayload。
type memoryDecisionQueryPayload struct {
	Entries      []map[string]any `json:"entries,omitempty"`
	DecisionHits []map[string]any `json:"decision_hits,omitempty"`
}

// memoryDecisionStatsPayload 对齐 core/shared/schema.json 的 memoryDecisionStatsPayload。
type memoryDecisionStatsPayload struct {
	Namespace          string `json:"namespace,omitempty"`
	MemoCount          int    `json:"memo_count,omitempty"`
	RecipeCount        int    `json:"recipe_count,omitempty"`
	ClusterCount       int    `json:"cluster_count,omitempty"`
	SuccessCount       int    `json:"success_count,omitempty"`
	PartialCount       int    `json:"partial_count,omitempty"`
	FailureCount       int    `json:"failure_count,omitempty"`
	AwaitingHumanCount int    `json:"awaiting_human_count,omitempty"`
	CancelledCount     int    `json:"cancelled_count,omitempty"`
	HumanBlockedCount  int    `json:"human_blocked_count,omitempty"`
}

// memoryDecisionRebuildPayload 对齐 core/shared/schema.json 的 memoryDecisionRebuildPayload。
type memoryDecisionRebuildPayload struct {
	Namespace       string `json:"namespace,omitempty"`
	SessionsScanned int    `json:"sessions_scanned,omitempty"`
	MarkdownScanned int    `json:"markdown_scanned,omitempty"`
	MemosCaptured   int    `json:"memos_captured,omitempty"`
	RecipesCreated  int    `json:"recipes_created,omitempty"`
	RecipesUpdated  int    `json:"recipes_updated,omitempty"`
	ClustersUpdated int    `json:"clusters_updated,omitempty"`
	SkippedEntries  int    `json:"skipped_entries,omitempty"`
}

// sessionImageContent 对齐 core/shared/schema.json 的 sessionImageContent。
type sessionImageContent struct {
	Path     string `json:"path,omitempty"`
	URL      string `json:"url,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
	Width    int    `json:"width,omitempty"`
	Height   int    `json:"height,omitempty"`
	SHA256   string `json:"sha256,omitempty"`
	Bytes    int    `json:"bytes,omitempty"`
}

// sessionContentPart 对齐 core/shared/schema.json 的 sessionContentPart。
type sessionContentPart struct {
	Type  string               `json:"type"`
	Text  string               `json:"text,omitempty"`
	Image *sessionImageContent `json:"image,omitempty"`
}

// sessionToolCall 对齐 core/shared/schema.json 的 sessionToolCall。
type sessionToolCall struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Arguments map[string]any `json:"arguments"`
}

// sessionToolResult 对齐 core/shared/schema.json 的 sessionToolResult。
type sessionToolResult struct {
	Status  string `json:"status"`
	Tool    string `json:"tool"`
	TraceID string `json:"trace_id,omitempty"`
	Output  string `json:"output,omitempty"`
	Error   string `json:"error,omitempty"`
}

// sessionHumanInteraction 对齐 core/shared/schema.json 的 sessionHumanInteraction。
type sessionHumanInteraction struct {
	QuestionID string `json:"question_id"`
	Prompt     string `json:"prompt"`
	Answer     string `json:"answer,omitempty"`
}

// sessionMessage 对齐 core/shared/schema.json 的 sessionMessage。
type sessionMessage struct {
	Role             string                   `json:"role"`
	Text             string                   `json:"text,omitempty"`
	Content          []sessionContentPart     `json:"content,omitempty"`
	ToolCalls        []sessionToolCall        `json:"tool_calls,omitempty"`
	ToolResult       *sessionToolResult       `json:"tool_result,omitempty"`
	HumanInteraction *sessionHumanInteraction `json:"human_interaction,omitempty"`
	ToolCallID       string                   `json:"tool_call_id,omitempty"`
}

// sessionMetadata 对齐 core/shared/schema.json 的 sessionMetadata。
type sessionMetadata struct {
	ID           string `json:"id"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	MessageCount int    `json:"message_count"`
	TokenCount   int    `json:"token_count"`
}

// sessionDetail 对齐 core/shared/schema.json 的 sessionDetail。
type sessionDetail struct {
	ID         string           `json:"id"`
	Messages   []sessionMessage `json:"messages"`
	CreatedAt  string           `json:"created_at"`
	UpdatedAt  string           `json:"updated_at"`
	TokenCount int              `json:"token_count"`
}

// configResponse 对齐 core/shared/schema.json 的 bridgeConfig。
type configResponse struct {
	Provider     string `json:"provider"`
	ProviderType string `json:"provider_type"`
	BaseURL      string `json:"base_url"`
	Model        string `json:"model"`
	ChatPath     string `json:"chat_path"`
	APIKeySet    bool   `json:"api_key_set"`
}

// configUpdateRequest 对齐 core/shared/schema.json 的 configUpdate。
type configUpdateRequest struct {
	Provider *string `json:"provider,omitempty"`
	APIKey   *string `json:"api_key,omitempty"`
	BaseURL  *string `json:"base_url,omitempty"`
	Model    *string `json:"model,omitempty"`
	ChatPath *string `json:"chat_path,omitempty"`
	TraceID  string  `json:"trace_id,omitempty"`
}

// providerConfigResponse 对齐 core/shared/schema.json 的 providerConfig。
type providerConfigResponse struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	BaseURL   string   `json:"base_url"`
	Models    []string `json:"models,omitempty"`
	APIKeySet bool     `json:"api_key_set"`
}

// providerConfigInput 对齐 core/shared/schema.json 的 providerConfigInput。
type providerConfigInput struct {
	Name    string   `json:"name"`
	Type    string   `json:"type"`
	BaseURL *string  `json:"base_url,omitempty"`
	APIKey  *string  `json:"api_key,omitempty"`
	Models  []string `json:"models,omitempty"`
	TraceID string   `json:"trace_id,omitempty"`
}

// providerListResponse 对齐 core/shared/schema.json 的 providerListResponse。
type providerListResponse struct {
	Providers      []providerConfigResponse `json:"providers"`
	ActiveProvider string                   `json:"active_provider"`
}

// setActiveProviderRequest 对齐 core/shared/schema.json 的 setActiveProviderRequest。
type setActiveProviderRequest struct {
	Name    string `json:"name"`
	TraceID string `json:"trace_id,omitempty"`
}

// apiRequest 对齐 core/shared/schema.json 的 requestEnvelope。
type apiRequest struct {
	Action    string          `json:"action"`
	Params    json.RawMessage `json:"params"`
	TraceID   string          `json:"trace_id"`
	RequestID string          `json:"request_id,omitempty"`
}

// apiResponse 对齐 core/shared/schema.json 的 responseEnvelope。
type apiResponse struct {
	Status    string `json:"status"`
	Payload   any    `json:"payload"`
	Error     string `json:"error"`
	RequestID string `json:"request_id,omitempty"`
}
