// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package app

import "encoding/json"

const (
	busActionPing          = "PING"
	busActionAgentSend     = "AGENT_SEND"
	busActionHumanResponse = "HUMAN_RESPONSE"
	busActionConfigGet     = "CONFIG_GET"
	busActionConfigUpdate  = "CONFIG_UPDATE"
	busActionMemoryQuery   = "MEMORY_QUERY"
	busActionMemoryArchive = "MEMORY_ARCHIVE"
	busActionListFiles     = "LIST_FILES"
	busActionBashExec      = "BASH_EXEC"
	busActionScriptExec    = "SCRIPT_EXEC"
	busActionScreenShot    = "SCREEN_SHOT"
	busActionMouseClick    = "MOUSE_CLICK"
	busActionBrowserQuery  = "BROWSER_QUERY"
)

const (
	busStatusSuccess = "success"
	busStatusError   = "error"
)

// apiRequest 对齐 core/shared/schema.json 的 requestEnvelope。
type apiRequest struct {
	Action  string          `json:"action"`
	Params  json.RawMessage `json:"params"`
	TraceID string          `json:"trace_id"`
}

// apiResponse 对齐 core/shared/schema.json 的 responseEnvelope。
type apiResponse struct {
	Status  string `json:"status"`
	Payload any    `json:"payload"`
	Error   string `json:"error"`
}
