package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
)

const (
	sourcePath = "../prompts.yaml"
	outputPath = "prompt_default_generated.go"
)

func main() {
	content, err := os.ReadFile(filepath.Clean(sourcePath))
	if err != nil {
		log.Fatalf("read prompt source: %v", err)
	}

	source := fmt.Sprintf(
		"// Code generated by go generate; DO NOT EDIT.\n\npackage context\n\nconst defaultPromptConfigYAML = %q\n",
		string(content),
	)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		log.Fatalf("format generated prompt source: %v", err)
	}
	if err := os.WriteFile(filepath.Clean(outputPath), formatted, 0o644); err != nil {
		log.Fatalf("write generated prompt source: %v", err)
	}
}
