// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package dev.ghostos.android.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
sealed interface AgentSendResponse

@Serializable
data class AssistantSessionEndSignal(
    val signal: String,
    val message: String
)

@Serializable
data class AgentRequest(
    val mode: String? = null,
    val message: String? = null,
    val images: List<SessionImageContent>? = null,
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("project_root")
    val projectRoot: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class AgentIterationSummaryItem(
    val iteration: Int,
    val did: String,
    val remaining: String,
    val completed: Boolean? = null,
    @SerialName("trace_id")
    val traceId: String? = null,
    @SerialName("recorded_at")
    val recordedAt: String? = null,
    @SerialName("final_change_log")
    val finalChangeLog: String? = null
)

@Serializable
data class AskHumanOption(
    val label: String,
    @SerialName("allow_custom")
    val allowCustom: Boolean? = null
)

@Serializable
data class AgentSendSuccessResponse(
    val message: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("session_ended")
    val sessionEnded: Boolean,
    val mode: String? = null,
    @SerialName("iteration_count")
    val iterationCount: Int? = null,
    @SerialName("stopped_by")
    val stoppedBy: String? = null,
    @SerialName("final_change_log")
    val finalChangeLog: String? = null,
    @SerialName("iteration_summary")
    val iterationSummary: List<AgentIterationSummaryItem>? = null,
    @SerialName("session_end")
    val sessionEnd: AssistantSessionEndSignal? = null
) : AgentSendResponse

@Serializable
data class AgentAwaitingHumanResponse(
    val status: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val prompt: String,
    @SerialName("selection_mode")
    val selectionMode: String? = null,
    val options: List<AskHumanOption>? = null
) : AgentSendResponse

@Serializable
data class AgentStopResponsePayload(
    val status: String,
    val message: String,
    @SerialName("session_id")
    val sessionId: String? = null
)

@Serializable
data class HumanResponseRequest(
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val answer: String,
    val cancelled: Boolean? = null
)

@Serializable
data class HumanResponseAck(
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val accepted: Boolean
)
