// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package dev.ghostos.android.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
data class ApiRequest<TParams>(
    val action: String,
    val params: TParams,
    @SerialName("trace_id") val traceId: String,
    @SerialName("request_id") val requestId: String? = null
)

@Serializable
data class ApiEnvelope<TPayload>(
    val status: String,
    val payload: TPayload? = null,
    val error: String = ""
)

sealed interface AgentSendResponse

sealed interface TaskCreateRequest

sealed interface TaskPayload

@Serializable
data class AssistantSessionEndSignal(
    val signal: String,
    val message: String
)

@Serializable
data class AgentRequest(
    val message: String,
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class AgentIterationSummaryItem(
    val iteration: Int,
    val did: String,
    val remaining: String,
    val completed: Boolean? = null,
    @SerialName("trace_id")
    val traceId: String? = null,
    @SerialName("recorded_at")
    val recordedAt: String? = null,
    @SerialName("final_change_log")
    val finalChangeLog: String? = null
)

@Serializable
data class AskHumanOption(
    val label: String,
    @SerialName("allow_custom")
    val allowCustom: Boolean? = null
)

@Serializable
data class AgentSendSuccessResponse(
    val message: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("session_ended")
    val sessionEnded: Boolean,
    val mode: String? = null,
    @SerialName("iteration_count")
    val iterationCount: Int? = null,
    @SerialName("stopped_by")
    val stoppedBy: String? = null,
    @SerialName("final_change_log")
    val finalChangeLog: String? = null,
    @SerialName("iteration_summary")
    val iterationSummary: List<AgentIterationSummaryItem>? = null,
    @SerialName("session_end")
    val sessionEnd: AssistantSessionEndSignal? = null
) : AgentSendResponse

@Serializable
data class AgentAwaitingHumanResponse(
    val status: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val prompt: String,
    @SerialName("selection_mode")
    val selectionMode: String? = null,
    val options: List<AskHumanOption>? = null
) : AgentSendResponse

@Serializable
data class AgentStopResponsePayload(
    val status: String,
    val message: String
)

@Serializable
data class HumanResponseRequest(
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val answer: String,
    val cancelled: Boolean? = null
)

@Serializable
data class HumanResponseAck(
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val accepted: Boolean
)

@Serializable
data class AgentStreamEvent(
    val id: String,
    @SerialName("step_id")
    val stepId: String,
    @SerialName("trace_id")
    val traceId: String,
    @SerialName("session_id")
    val sessionId: String? = null,
    val turn: Int,
    val type: String,
    val payload: JsonObject,
    val at: String? = null
)

@Serializable
data class SessionImageContent(
    val path: String? = null,
    val url: String? = null,
    @SerialName("mime_type")
    val mimeType: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val sha256: String? = null,
    val bytes: Int? = null
)

@Serializable
data class SessionFileContent(
    @SerialName("artifact_id")
    val artifactId: String,
    val name: String,
    @SerialName("mime_type")
    val mimeType: String? = null,
    val bytes: Int? = null,
    val sha256: String? = null,
    @SerialName("download_url")
    val downloadUrl: String,
    @SerialName("source_path")
    val sourcePath: String? = null,
    val note: String? = null
)

@Serializable
data class SessionPushEvent(
    val id: String,
    val type: String,
    @SerialName("trace_id")
    val traceId: String? = null,
    @SerialName("session_id")
    val sessionId: String,
    val payload: JsonObject,
    val at: String? = null
)

@Serializable
data class AgentRunStartedPayload(
    @SerialName("session_id")
    val sessionId: String? = null
)

@Serializable
data class SessionContentPart(
    val type: String,
    val text: String? = null,
    val image: SessionImageContent? = null,
    val file: SessionFileContent? = null
)

@Serializable
data class AgentCompletionDeltaPayload(
    val kind: String,
    val text: String? = null,
    @SerialName("tool_call_index")
    val toolCallIndex: Int? = null,
    @SerialName("tool_call_id")
    val toolCallId: String? = null,
    @SerialName("tool_name")
    val toolName: String? = null,
    @SerialName("arguments_fragment")
    val argumentsFragment: String? = null
)

@Serializable
data class SessionToolCall(
    val id: String,
    val name: String,
    val arguments: JsonObject
)

@Serializable
data class AgentToolCallStartedPayload(
    val tool: String? = null,
    @SerialName("tool_call_id")
    val toolCallId: String? = null
)

@Serializable
data class SessionToolResult(
    val status: String,
    val tool: String,
    @SerialName("trace_id")
    val traceId: String? = null,
    val output: String? = null,
    val error: String? = null
)

@Serializable
data class AgentToolCallFinishedPayload(
    val tool: String? = null,
    @SerialName("tool_call_id")
    val toolCallId: String? = null,
    val status: String? = null,
    val error: String? = null
)

@Serializable
data class SessionHumanInteraction(
    @SerialName("question_id")
    val questionId: String,
    val prompt: String,
    @SerialName("selection_mode")
    val selectionMode: String? = null,
    val options: List<AskHumanOption>? = null,
    val answer: String? = null
)

@Serializable
data class AgentStreamMessagePayload(
    val text: String,
    @SerialName("session_id")
    val sessionId: String? = null
)

@Serializable
data class SessionMessage(
    val role: String,
    val text: String? = null,
    val content: List<SessionContentPart>? = null,
    @SerialName("tool_calls")
    val toolCalls: List<SessionToolCall>? = null,
    @SerialName("tool_result")
    val toolResult: SessionToolResult? = null,
    @SerialName("human_interaction")
    val humanInteraction: SessionHumanInteraction? = null,
    @SerialName("tool_call_id")
    val toolCallId: String? = null
)

@Serializable
data class AgentDonePayload(
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("session_ended")
    val sessionEnded: Boolean? = null
)

@Serializable
data class SessionMetadata(
    val id: String,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("message_count")
    val messageCount: Int,
    @SerialName("token_count")
    val tokenCount: Int
)

@Serializable
data class AgentErrorPayload(
    val message: String,
    @SerialName("session_id")
    val sessionId: String? = null,
    val code: Int? = null
)

@Serializable
data class SessionDetail(
    val id: String,
    val messages: List<SessionMessage>,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("token_count")
    val tokenCount: Int
)

@Serializable
data class BridgeConfig(
    val provider: String,
    @SerialName("provider_type")
    val providerType: String,
    @SerialName("base_url")
    val baseUrl: String,
    val model: String,
    @SerialName("chat_path")
    val chatPath: String,
    @SerialName("api_key_set")
    val apiKeySet: Boolean,
    @SerialName("model_selection_enabled")
    val modelSelectionEnabled: Boolean,
    @SerialName("graphql_default_source")
    val graphqlDefaultSource: String,
    @SerialName("graphql_tool_runtime_enabled")
    val graphqlToolRuntimeEnabled: Boolean,
    @SerialName("graphql_sources")
    val graphqlSources: List<GraphQLSourceResponse>,
    @SerialName("graphql_mutation_policies")
    val graphqlMutationPolicies: List<GraphQLMutationPolicyResponse>,
    @SerialName("web_rooter_enabled")
    val webRooterEnabled: Boolean,
    @SerialName("web_rooter_api_token_set")
    val webRooterApiTokenSet: Boolean,
    @SerialName("web_search_tavily_api_key_set")
    val webSearchTavilyApiKeySet: Boolean,
    @SerialName("web_search_exa_api_key_set")
    val webSearchExaApiKeySet: Boolean
)

@Serializable
data class SessionPushAssistantMessagePayload(
    val message: String,
    @SerialName("session_ended")
    val sessionEnded: Boolean,
    @SerialName("session_end")
    val sessionEnd: AssistantSessionEndSignal? = null
)

@Serializable
data class ConfigUpdate(
    val provider: String? = null,
    @SerialName("api_key")
    val apiKey: String? = null,
    @SerialName("base_url")
    val baseUrl: String? = null,
    val model: String? = null,
    @SerialName("chat_path")
    val chatPath: String? = null,
    @SerialName("graphql_default_source")
    val graphqlDefaultSource: String? = null,
    @SerialName("graphql_tool_runtime_enabled")
    val graphqlToolRuntimeEnabled: Boolean? = null,
    @SerialName("graphql_sources")
    val graphqlSources: List<GraphQLSourceInput>? = null,
    @SerialName("graphql_source_upsert")
    val graphqlSourceUpsert: GraphQLSourceInput? = null,
    @SerialName("graphql_mutation_policies")
    val graphqlMutationPolicies: List<GraphQLMutationPolicyInput>? = null,
    @SerialName("web_rooter_enabled")
    val webRooterEnabled: Boolean? = null,
    @SerialName("web_rooter_base_url")
    val webRooterBaseUrl: String? = null,
    @SerialName("web_rooter_api_token")
    val webRooterApiToken: String? = null,
    @SerialName("web_rooter_timeout_ms")
    val webRooterTimeoutMs: Int? = null,
    @SerialName("web_search_tavily_api_key")
    val webSearchTavilyApiKey: String? = null,
    @SerialName("web_search_exa_api_key")
    val webSearchExaApiKey: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class SessionPushAwaitingHumanPayload(
    @SerialName("question_id")
    val questionId: String,
    val prompt: String,
    @SerialName("selection_mode")
    val selectionMode: String? = null,
    val options: List<AskHumanOption>? = null
)

@Serializable
data class GraphQLDomainResponse(
    val name: String,
    val description: String? = null,
    @SerialName("root_queries")
    val rootQueries: List<String>,
    val types: List<String>? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null
)

@Serializable
data class GraphQLSourceResponse(
    val name: String,
    val description: String? = null,
    val endpoint: String,
    @SerialName("schema_path")
    val schemaPath: String,
    @SerialName("timeout_ms")
    val timeoutMs: Int,
    @SerialName("max_response_bytes")
    val maxResponseBytes: Int,
    @SerialName("max_depth")
    val maxDepth: Int,
    @SerialName("max_fields")
    val maxFields: Int,
    @SerialName("max_root_fields")
    val maxRootFields: Int,
    @SerialName("max_fragments")
    val maxFragments: Int,
    val headers: Map<String, String>? = null,
    @SerialName("api_key_set")
    val apiKeySet: Boolean,
    val domains: List<GraphQLDomainResponse>? = null
)

@Serializable
data class GraphQLDomainInput(
    val name: String,
    val description: String? = null,
    @SerialName("root_queries")
    val rootQueries: List<String>,
    val types: List<String>? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null
)

@Serializable
data class GraphQLMutationPolicyResponse(
    val name: String,
    val description: String? = null,
    val source: String,
    val domain: String,
    @SerialName("root_mutation")
    val rootMutation: String,
    @SerialName("approval_required")
    val approvalRequired: Boolean? = null,
    @SerialName("idempotency_mode")
    val idempotencyMode: String,
    @SerialName("idempotency_header")
    val idempotencyHeader: String? = null,
    @SerialName("idempotency_variable_path")
    val idempotencyVariablePath: String? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null,
    @SerialName("max_fragments")
    val maxFragments: Int? = null
)

@Serializable
data class GraphQLMutationPolicyInput(
    val name: String,
    val description: String? = null,
    val source: String,
    val domain: String,
    @SerialName("root_mutation")
    val rootMutation: String,
    @SerialName("approval_required")
    val approvalRequired: Boolean? = null,
    @SerialName("idempotency_mode")
    val idempotencyMode: String,
    @SerialName("idempotency_header")
    val idempotencyHeader: String? = null,
    @SerialName("idempotency_variable_path")
    val idempotencyVariablePath: String? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null,
    @SerialName("max_fragments")
    val maxFragments: Int? = null
)

@Serializable
data class GraphQLSourceInput(
    val name: String,
    val description: String? = null,
    val endpoint: String,
    @SerialName("api_key")
    val apiKey: String? = null,
    @SerialName("schema_path")
    val schemaPath: String,
    @SerialName("timeout_ms")
    val timeoutMs: Int? = null,
    @SerialName("max_response_bytes")
    val maxResponseBytes: Int? = null,
    val headers: Map<String, String>? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null,
    @SerialName("max_fragments")
    val maxFragments: Int? = null,
    val domains: List<GraphQLDomainInput>? = null
)

@Serializable
data class ProviderConfig(
    val name: String,
    val type: String,
    @SerialName("base_url")
    val baseUrl: String,
    val models: List<String>? = null,
    @SerialName("context_window_tokens")
    val contextWindowTokens: Int? = null,
    @SerialName("response_reserve_tokens")
    val responseReserveTokens: Int? = null,
    @SerialName("model_context_window_tokens")
    val modelContextWindowTokens: Map<String, Int>? = null,
    @SerialName("model_response_reserve_tokens")
    val modelResponseReserveTokens: Map<String, Int>? = null,
    @SerialName("api_key_set")
    val apiKeySet: Boolean
)

@Serializable
data class ProviderConfigInput(
    val name: String,
    val type: String,
    @SerialName("base_url")
    val baseUrl: String? = null,
    @SerialName("api_key")
    val apiKey: String? = null,
    val models: List<String>? = null,
    @SerialName("context_window_tokens")
    val contextWindowTokens: Int? = null,
    @SerialName("response_reserve_tokens")
    val responseReserveTokens: Int? = null,
    @SerialName("model_context_window_tokens")
    val modelContextWindowTokens: Map<String, Int>? = null,
    @SerialName("model_response_reserve_tokens")
    val modelResponseReserveTokens: Map<String, Int>? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class ProviderListResponse(
    val providers: List<ProviderConfig>,
    @SerialName("active_provider")
    val activeProvider: String
)

@Serializable
data class SetActiveProviderRequest(
    val name: String,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class WorkflowNode(
    val id: String,
    val type: String,
    val tool: WorkflowToolNode? = null,
    val llm: WorkflowLLMNode? = null,
    val agent: WorkflowAgentNode? = null
)

@Serializable
data class WorkflowEdge(
    @SerialName("from_node_id")
    val fromNodeId: String,
    @SerialName("to_node_id")
    val toNodeId: String
)

@Serializable
data class WorkflowDefinition(
    val nodes: List<WorkflowNode>,
    val edges: List<WorkflowEdge>
)

@Serializable
data class RSSInboxPollTaskActionParams(
    @SerialName("max_items_per_feed")
    val maxItemsPerFeed: Int? = null,
    @SerialName("ai_batch_size")
    val aiBatchSize: Int? = null
)

@Serializable
data class RSSBriefingTaskActionParams(
    @SerialName("feed_id")
    val feedId: String? = null,
    val tag: String? = null,
    val importance: String? = null,
    @SerialName("window_hours")
    val windowHours: Int? = null,
    @SerialName("group_limit")
    val groupLimit: Int? = null,
    @SerialName("item_limit")
    val itemLimit: Int? = null,
    @SerialName("items_per_group")
    val itemsPerGroup: Int? = null,
    @SerialName("highlights_limit")
    val highlightsLimit: Int? = null
)

@Serializable
data class AgentMessageTaskCreateRequest(
    val message: String,
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("task_kind")
    val taskKind: String? = null,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
) : TaskCreateRequest

@Serializable
data class WorkflowToolNode(
    @SerialName("tool_name")
    val toolName: String,
    val arguments: JsonObject? = null
)

@Serializable
data class RSSInboxPollTaskCreateRequest(
    @SerialName("task_kind")
    val taskKind: String,
    val action: String,
    @SerialName("action_params")
    val actionParams: RSSInboxPollTaskActionParams? = null,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
) : TaskCreateRequest

@Serializable
data class WorkflowLLMNode(
    val prompt: String,
    @SerialName("system_prompt")
    val systemPrompt: String? = null
)

@Serializable
data class RSSBriefingTaskCreateRequest(
    @SerialName("task_kind")
    val taskKind: String,
    val action: String,
    @SerialName("action_params")
    val actionParams: RSSBriefingTaskActionParams? = null,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
) : TaskCreateRequest

@Serializable
data class WorkflowAgentNode(
    val message: String
)

@Serializable
data class WorkflowTaskCreateRequest(
    @SerialName("task_kind")
    val taskKind: String,
    val workflow: WorkflowDefinition,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
) : TaskCreateRequest

@Serializable
data class TaskUpdateRequest(
    val id: String,
    val message: String? = null,
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("task_kind")
    val taskKind: String? = null,
    val action: String? = null,
    @SerialName("action_params")
    val actionParams: JsonObject? = null,
    val workflow: WorkflowDefinition? = null,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    val enabled: Boolean? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class AgentMessageTaskPayload(
    val id: String,
    val message: String,
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("task_kind")
    val taskKind: String,
    @SerialName("schedule_type")
    val scheduleType: String,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    val enabled: Boolean,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("last_run_at")
    val lastRunAt: String? = null,
    @SerialName("next_run_at")
    val nextRunAt: String? = null,
    @SerialName("last_error")
    val lastError: String? = null
) : TaskPayload

@Serializable
data class RSSInboxPollTaskPayload(
    val id: String,
    @SerialName("task_kind")
    val taskKind: String,
    val action: String,
    @SerialName("action_params")
    val actionParams: RSSInboxPollTaskActionParams? = null,
    @SerialName("schedule_type")
    val scheduleType: String,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    val enabled: Boolean,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("last_run_at")
    val lastRunAt: String? = null,
    @SerialName("next_run_at")
    val nextRunAt: String? = null,
    @SerialName("last_error")
    val lastError: String? = null
) : TaskPayload

@Serializable
data class RSSBriefingTaskPayload(
    val id: String,
    @SerialName("task_kind")
    val taskKind: String,
    val action: String,
    @SerialName("action_params")
    val actionParams: RSSBriefingTaskActionParams? = null,
    @SerialName("schedule_type")
    val scheduleType: String,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    val enabled: Boolean,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("last_run_at")
    val lastRunAt: String? = null,
    @SerialName("next_run_at")
    val nextRunAt: String? = null,
    @SerialName("last_error")
    val lastError: String? = null
) : TaskPayload

@Serializable
data class WorkflowTaskPayload(
    val id: String,
    @SerialName("task_kind")
    val taskKind: String,
    val workflow: WorkflowDefinition,
    @SerialName("schedule_type")
    val scheduleType: String,
    @SerialName("interval_seconds")
    val intervalSeconds: Int? = null,
    @SerialName("cron_expr")
    val cronExpr: String? = null,
    val enabled: Boolean,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("last_run_at")
    val lastRunAt: String? = null,
    @SerialName("next_run_at")
    val nextRunAt: String? = null,
    @SerialName("last_error")
    val lastError: String? = null
) : TaskPayload
