// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package dev.ghostos.android.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
data class ApiRequest<TParams>(
    val action: String,
    val params: TParams,
    @SerialName("trace_id") val traceId: String,
    @SerialName("request_id") val requestId: String? = null
)

@Serializable
data class ApiEnvelope<TPayload>(
    val status: String,
    val payload: TPayload? = null,
    val error: String = ""
)

sealed interface AgentSendResponse

@Serializable
data class AssistantSessionEndSignal(
    val signal: String,
    val message: String
)

@Serializable
data class AgentRequest(
    val message: String,
    @SerialName("session_id")
    val sessionId: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class AskHumanOption(
    val label: String,
    @SerialName("allow_custom")
    val allowCustom: Boolean? = null
)

@Serializable
data class AgentSendSuccessResponse(
    val message: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("session_ended")
    val sessionEnded: Boolean,
    val mode: String? = null,
    @SerialName("iteration_count")
    val iterationCount: Int? = null,
    @SerialName("stopped_by")
    val stoppedBy: String? = null,
    @SerialName("final_change_log")
    val finalChangeLog: String? = null,
    @SerialName("iteration_summary")
    val iterationSummary: List<JsonObject>? = null,
    @SerialName("session_end")
    val sessionEnd: AssistantSessionEndSignal? = null
) : AgentSendResponse

@Serializable
data class AgentAwaitingHumanResponse(
    val status: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val prompt: String,
    @SerialName("selection_mode")
    val selectionMode: String? = null,
    val options: List<AskHumanOption>? = null
) : AgentSendResponse

@Serializable
data class AgentStopResponsePayload(
    val status: String,
    val message: String
)

@Serializable
data class HumanResponseRequest(
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val answer: String,
    val cancelled: Boolean? = null
)

@Serializable
data class HumanResponseAck(
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("question_id")
    val questionId: String,
    val accepted: Boolean
)

@Serializable
data class SessionImageContent(
    val path: String? = null,
    val url: String? = null,
    @SerialName("mime_type")
    val mimeType: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val sha256: String? = null,
    val bytes: Int? = null
)

@Serializable
data class SessionFileContent(
    @SerialName("artifact_id")
    val artifactId: String,
    val name: String,
    @SerialName("mime_type")
    val mimeType: String? = null,
    val bytes: Int? = null,
    val sha256: String? = null,
    @SerialName("download_url")
    val downloadUrl: String,
    @SerialName("source_path")
    val sourcePath: String? = null,
    val note: String? = null
)

@Serializable
data class SessionContentPart(
    val type: String,
    val text: String? = null,
    val image: SessionImageContent? = null,
    val file: SessionFileContent? = null
)

@Serializable
data class SessionToolCall(
    val id: String,
    val name: String,
    val arguments: JsonObject
)

@Serializable
data class SessionToolResult(
    val status: String,
    val tool: String,
    @SerialName("trace_id")
    val traceId: String? = null,
    val output: String? = null,
    val error: String? = null
)

@Serializable
data class SessionHumanInteraction(
    @SerialName("question_id")
    val questionId: String,
    val prompt: String,
    @SerialName("selection_mode")
    val selectionMode: String? = null,
    val options: List<AskHumanOption>? = null,
    val answer: String? = null
)

@Serializable
data class SessionMessage(
    val role: String,
    val text: String? = null,
    val content: List<SessionContentPart>? = null,
    @SerialName("tool_calls")
    val toolCalls: List<SessionToolCall>? = null,
    @SerialName("tool_result")
    val toolResult: SessionToolResult? = null,
    @SerialName("human_interaction")
    val humanInteraction: SessionHumanInteraction? = null,
    @SerialName("tool_call_id")
    val toolCallId: String? = null
)

@Serializable
data class SessionMetadata(
    val id: String,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("message_count")
    val messageCount: Int,
    @SerialName("token_count")
    val tokenCount: Int
)

@Serializable
data class SessionDetail(
    val id: String,
    val messages: List<SessionMessage>,
    @SerialName("created_at")
    val createdAt: String,
    @SerialName("updated_at")
    val updatedAt: String,
    @SerialName("token_count")
    val tokenCount: Int
)

@Serializable
data class BridgeConfig(
    val provider: String,
    @SerialName("provider_type")
    val providerType: String,
    @SerialName("base_url")
    val baseUrl: String,
    val model: String,
    @SerialName("chat_path")
    val chatPath: String,
    @SerialName("api_key_set")
    val apiKeySet: Boolean,
    @SerialName("model_selection_enabled")
    val modelSelectionEnabled: Boolean,
    @SerialName("graphql_default_source")
    val graphqlDefaultSource: String,
    @SerialName("graphql_sources")
    val graphqlSources: List<GraphQLSourceResponse>,
    @SerialName("graphql_mutation_policies")
    val graphqlMutationPolicies: List<GraphQLMutationPolicyResponse>,
    @SerialName("web_search_tavily_api_key_set")
    val webSearchTavilyApiKeySet: Boolean,
    @SerialName("web_search_exa_api_key_set")
    val webSearchExaApiKeySet: Boolean
)

@Serializable
data class ConfigUpdate(
    val provider: String? = null,
    @SerialName("api_key")
    val apiKey: String? = null,
    @SerialName("base_url")
    val baseUrl: String? = null,
    val model: String? = null,
    @SerialName("chat_path")
    val chatPath: String? = null,
    @SerialName("graphql_default_source")
    val graphqlDefaultSource: String? = null,
    @SerialName("graphql_sources")
    val graphqlSources: List<GraphQLSourceInput>? = null,
    @SerialName("graphql_source_upsert")
    val graphqlSourceUpsert: GraphQLSourceInput? = null,
    @SerialName("graphql_mutation_policies")
    val graphqlMutationPolicies: List<GraphQLMutationPolicyInput>? = null,
    @SerialName("web_search_tavily_api_key")
    val webSearchTavilyApiKey: String? = null,
    @SerialName("web_search_exa_api_key")
    val webSearchExaApiKey: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class GraphQLDomainResponse(
    val name: String,
    val description: String? = null,
    @SerialName("root_queries")
    val rootQueries: List<String>,
    val types: List<String>? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null
)

@Serializable
data class GraphQLSourceResponse(
    val name: String,
    val description: String? = null,
    val endpoint: String,
    @SerialName("schema_path")
    val schemaPath: String,
    @SerialName("timeout_ms")
    val timeoutMs: Int,
    @SerialName("max_response_bytes")
    val maxResponseBytes: Int,
    @SerialName("max_depth")
    val maxDepth: Int,
    @SerialName("max_fields")
    val maxFields: Int,
    @SerialName("max_root_fields")
    val maxRootFields: Int,
    @SerialName("max_fragments")
    val maxFragments: Int,
    val headers: JsonObject? = null,
    @SerialName("api_key_set")
    val apiKeySet: Boolean,
    val domains: List<GraphQLDomainResponse>? = null
)

@Serializable
data class GraphQLDomainInput(
    val name: String,
    val description: String? = null,
    @SerialName("root_queries")
    val rootQueries: List<String>,
    val types: List<String>? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null
)

@Serializable
data class GraphQLMutationPolicyResponse(
    val name: String,
    val description: String? = null,
    val source: String,
    val domain: String,
    @SerialName("root_mutation")
    val rootMutation: String,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null,
    @SerialName("max_fragments")
    val maxFragments: Int? = null
)

@Serializable
data class GraphQLMutationPolicyInput(
    val name: String,
    val description: String? = null,
    val source: String,
    val domain: String,
    @SerialName("root_mutation")
    val rootMutation: String,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null,
    @SerialName("max_fragments")
    val maxFragments: Int? = null
)

@Serializable
data class GraphQLSourceInput(
    val name: String,
    val description: String? = null,
    val endpoint: String,
    @SerialName("api_key")
    val apiKey: String? = null,
    @SerialName("schema_path")
    val schemaPath: String,
    @SerialName("timeout_ms")
    val timeoutMs: Int? = null,
    @SerialName("max_response_bytes")
    val maxResponseBytes: Int? = null,
    val headers: JsonObject? = null,
    @SerialName("max_depth")
    val maxDepth: Int? = null,
    @SerialName("max_fields")
    val maxFields: Int? = null,
    @SerialName("max_root_fields")
    val maxRootFields: Int? = null,
    @SerialName("max_fragments")
    val maxFragments: Int? = null,
    val domains: List<GraphQLDomainInput>? = null
)

@Serializable
data class ProviderConfig(
    val name: String,
    val type: String,
    @SerialName("base_url")
    val baseUrl: String,
    val models: List<String>? = null,
    @SerialName("context_window_tokens")
    val contextWindowTokens: Int? = null,
    @SerialName("response_reserve_tokens")
    val responseReserveTokens: Int? = null,
    @SerialName("model_context_window_tokens")
    val modelContextWindowTokens: JsonObject? = null,
    @SerialName("model_response_reserve_tokens")
    val modelResponseReserveTokens: JsonObject? = null,
    @SerialName("api_key_set")
    val apiKeySet: Boolean
)

@Serializable
data class ProviderConfigInput(
    val name: String,
    val type: String,
    @SerialName("base_url")
    val baseUrl: String? = null,
    @SerialName("api_key")
    val apiKey: String? = null,
    val models: List<String>? = null,
    @SerialName("context_window_tokens")
    val contextWindowTokens: Int? = null,
    @SerialName("response_reserve_tokens")
    val responseReserveTokens: Int? = null,
    @SerialName("model_context_window_tokens")
    val modelContextWindowTokens: JsonObject? = null,
    @SerialName("model_response_reserve_tokens")
    val modelResponseReserveTokens: JsonObject? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class ProviderListResponse(
    val providers: List<ProviderConfig>,
    @SerialName("active_provider")
    val activeProvider: String
)

@Serializable
data class SetActiveProviderRequest(
    val name: String,
    @SerialName("trace_id")
    val traceId: String? = null
)
