// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

package dev.ghostos.android.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BridgeConfig(
    val provider: String,
    @SerialName("provider_type")
    val providerType: String,
    @SerialName("base_url")
    val baseUrl: String,
    val model: String,
    @SerialName("chat_path")
    val chatPath: String,
    @SerialName("project_root")
    val projectRoot: String,
    @SerialName("max_turns")
    val maxTurns: Int,
    @SerialName("task_execution_timeout_ms")
    val taskExecutionTimeoutMs: Int,
    @SerialName("llm_completion_retry_count")
    val llmCompletionRetryCount: Int,
    @SerialName("llm_completion_retry_interval_ms")
    val llmCompletionRetryIntervalMs: Int,
    @SerialName("api_key_set")
    val apiKeySet: Boolean,
    @SerialName("model_selection_enabled")
    val modelSelectionEnabled: Boolean,
    @SerialName("session_human_log_full_enabled")
    val sessionHumanLogFullEnabled: Boolean,
    @SerialName("session_system_prompt_visible_enabled")
    val sessionSystemPromptVisibleEnabled: Boolean,
    @SerialName("assistant_markdown_enabled")
    val assistantMarkdownEnabled: Boolean,
    @SerialName("tool_call_compact_output_enabled")
    val toolCallCompactOutputEnabled: Boolean,
    @SerialName("memory_mode_enabled")
    val memoryModeEnabled: Boolean,
    @SerialName("microcompact_enabled")
    val microcompactEnabled: Boolean,
    @SerialName("web_search_tavily_url")
    val webSearchTavilyUrl: String,
    @SerialName("web_search_exa_url")
    val webSearchExaUrl: String,
    @SerialName("web_search_tavily_api_key_set")
    val webSearchTavilyApiKeySet: Boolean,
    @SerialName("web_search_exa_api_key_set")
    val webSearchExaApiKeySet: Boolean
)

@Serializable
data class ConfigUpdate(
    val provider: String? = null,
    @SerialName("api_key")
    val apiKey: String? = null,
    @SerialName("base_url")
    val baseUrl: String? = null,
    val model: String? = null,
    @SerialName("chat_path")
    val chatPath: String? = null,
    @SerialName("project_root")
    val projectRoot: String? = null,
    @SerialName("max_turns")
    val maxTurns: Int? = null,
    @SerialName("task_execution_timeout_ms")
    val taskExecutionTimeoutMs: Int? = null,
    @SerialName("llm_completion_retry_count")
    val llmCompletionRetryCount: Int? = null,
    @SerialName("llm_completion_retry_interval_ms")
    val llmCompletionRetryIntervalMs: Int? = null,
    @SerialName("session_human_log_full_enabled")
    val sessionHumanLogFullEnabled: Boolean? = null,
    @SerialName("session_system_prompt_visible_enabled")
    val sessionSystemPromptVisibleEnabled: Boolean? = null,
    @SerialName("assistant_markdown_enabled")
    val assistantMarkdownEnabled: Boolean? = null,
    @SerialName("tool_call_compact_output_enabled")
    val toolCallCompactOutputEnabled: Boolean? = null,
    @SerialName("memory_mode_enabled")
    val memoryModeEnabled: Boolean? = null,
    @SerialName("microcompact_enabled")
    val microcompactEnabled: Boolean? = null,
    @SerialName("web_search_tavily_url")
    val webSearchTavilyUrl: String? = null,
    @SerialName("web_search_exa_url")
    val webSearchExaUrl: String? = null,
    @SerialName("web_search_tavily_api_key")
    val webSearchTavilyApiKey: String? = null,
    @SerialName("web_search_exa_api_key")
    val webSearchExaApiKey: String? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class ProviderConfig(
    val name: String,
    val type: String,
    @SerialName("base_url")
    val baseUrl: String,
    val models: List<String>? = null,
    @SerialName("context_window_tokens")
    val contextWindowTokens: Int? = null,
    @SerialName("response_reserve_tokens")
    val responseReserveTokens: Int? = null,
    @SerialName("model_context_window_tokens")
    val modelContextWindowTokens: Map<String, Int>? = null,
    @SerialName("model_response_reserve_tokens")
    val modelResponseReserveTokens: Map<String, Int>? = null,
    @SerialName("api_key_set")
    val apiKeySet: Boolean
)

@Serializable
data class ProviderConfigInput(
    val name: String,
    val type: String,
    @SerialName("base_url")
    val baseUrl: String? = null,
    @SerialName("api_key")
    val apiKey: String? = null,
    val models: List<String>? = null,
    @SerialName("context_window_tokens")
    val contextWindowTokens: Int? = null,
    @SerialName("response_reserve_tokens")
    val responseReserveTokens: Int? = null,
    @SerialName("model_context_window_tokens")
    val modelContextWindowTokens: Map<String, Int>? = null,
    @SerialName("model_response_reserve_tokens")
    val modelResponseReserveTokens: Map<String, Int>? = null,
    @SerialName("trace_id")
    val traceId: String? = null
)

@Serializable
data class ProviderListResponse(
    val providers: List<ProviderConfig>,
    @SerialName("active_provider")
    val activeProvider: String
)

@Serializable
data class SetActiveProviderRequest(
    val name: String,
    @SerialName("trace_id")
    val traceId: String? = null
)
