// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};

pub const ASSISTANT_SESSION_END_SIGNAL: &str = "END_SESSION";

#[derive(Debug, Serialize)]
pub struct ApiRequest<TParams> {
    pub action: &'static str,
    pub params: TParams,
    pub trace_id: String,
}

#[derive(Debug, Deserialize)]
pub struct ApiResponse<TPayload> {
    pub status: String,
    pub payload: Option<TPayload>,
    #[serde(default)]
    pub error: String,
}

impl<TPayload> ApiResponse<TPayload> {
    pub fn into_result(self) -> Result<TPayload> {
        if self.status == "success" {
            return self
                .payload
                .ok_or_else(|| anyhow!("bridge response payload is missing"));
        }
        let message = self.error.trim();
        if message.is_empty() {
            return Err(anyhow!("bridge returned an unknown error"));
        }
        Err(anyhow!(message.to_string()))
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistantSessionEndSignal {
    pub signal: String,
    pub message: String,
}
