// Code generated by core/shared/generate_envelope_types.py; DO NOT EDIT.
// Source: core/shared/schema.json (https://ghost-os.dev/schemas/bus-envelope.schema.json)

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use serde_json::Value;

#[derive(Debug, Serialize)]
pub struct ApiRequest<TParams> {
    pub action: &'static str,
    pub params: TParams,
    pub trace_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct ApiResponse<TPayload> {
    pub status: String,
    pub payload: Option<TPayload>,
    #[serde(default)]
    pub error: String,
}

impl<TPayload> ApiResponse<TPayload> {
    pub fn into_result(self) -> Result<TPayload> {
        if self.status == "success" {
            return self
                .payload
                .ok_or_else(|| anyhow!("bridge response payload is missing"));
        }
        let message = self.error.trim();
        if message.is_empty() {
            return Err(anyhow!("bridge returned an unknown error"));
        }
        Err(anyhow!(message.to_string()))
    }
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AssistantSessionEndSignal {
    pub signal: String,
    pub message: String,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentRequest {
    pub message: String,
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentIterationSummaryItem {
    pub iteration: i64,
    pub did: String,
    pub remaining: String,
    #[serde(default)]
    pub completed: Option<bool>,
    #[serde(default)]
    pub trace_id: Option<String>,
    #[serde(default)]
    pub recorded_at: Option<String>,
    #[serde(default)]
    pub final_change_log: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AskHumanOption {
    pub label: String,
    #[serde(default)]
    pub allow_custom: Option<bool>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentSendSuccessResponse {
    pub message: String,
    pub session_id: String,
    pub session_ended: bool,
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub iteration_count: Option<i64>,
    #[serde(default)]
    pub stopped_by: Option<String>,
    #[serde(default)]
    pub final_change_log: Option<String>,
    #[serde(default)]
    pub iteration_summary: Option<Vec<AgentIterationSummaryItem>>,
    #[serde(default)]
    pub session_end: Option<AssistantSessionEndSignal>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentSendAwaitingHumanResponse {
    pub status: String,
    pub session_id: String,
    pub question_id: String,
    pub prompt: String,
    #[serde(default)]
    pub selection_mode: Option<String>,
    #[serde(default)]
    pub options: Option<Vec<AskHumanOption>>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentStopResponsePayload {
    pub status: String,
    pub message: String,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct HumanResponseRequest {
    pub session_id: String,
    pub question_id: String,
    pub answer: String,
    #[serde(default)]
    pub cancelled: Option<bool>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct HumanResponseAck {
    pub session_id: String,
    pub question_id: String,
    pub accepted: bool,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentStreamEvent {
    pub id: String,
    pub step_id: String,
    pub trace_id: String,
    #[serde(default)]
    pub session_id: Option<String>,
    pub turn: i64,
    #[serde(rename = "type")]
    pub r#type: String,
    pub payload: BTreeMap<String, Value>,
    #[serde(default)]
    pub at: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionImageContent {
    #[serde(default)]
    pub path: Option<String>,
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub mime_type: Option<String>,
    #[serde(default)]
    pub width: Option<i64>,
    #[serde(default)]
    pub height: Option<i64>,
    #[serde(default)]
    pub sha256: Option<String>,
    #[serde(default)]
    pub bytes: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionFileContent {
    pub artifact_id: String,
    pub name: String,
    #[serde(default)]
    pub mime_type: Option<String>,
    #[serde(default)]
    pub bytes: Option<i64>,
    #[serde(default)]
    pub sha256: Option<String>,
    pub download_url: String,
    #[serde(default)]
    pub source_path: Option<String>,
    #[serde(default)]
    pub note: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionPushEvent {
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(default)]
    pub trace_id: Option<String>,
    pub session_id: String,
    pub payload: BTreeMap<String, Value>,
    #[serde(default)]
    pub at: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentRunStartedPayload {
    #[serde(default)]
    pub session_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionContentPart {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(default)]
    pub text: Option<String>,
    #[serde(default)]
    pub image: Option<SessionImageContent>,
    #[serde(default)]
    pub file: Option<SessionFileContent>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentCompletionDeltaPayload {
    pub kind: String,
    #[serde(default)]
    pub text: Option<String>,
    #[serde(default)]
    pub tool_call_index: Option<i64>,
    #[serde(default)]
    pub tool_call_id: Option<String>,
    #[serde(default)]
    pub tool_name: Option<String>,
    #[serde(default)]
    pub arguments_fragment: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionToolCall {
    pub id: String,
    pub name: String,
    pub arguments: BTreeMap<String, Value>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentToolCallStartedPayload {
    #[serde(default)]
    pub tool: Option<String>,
    #[serde(default)]
    pub tool_call_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionToolResult {
    pub status: String,
    pub tool: String,
    #[serde(default)]
    pub trace_id: Option<String>,
    #[serde(default)]
    pub output: Option<String>,
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentToolCallFinishedPayload {
    #[serde(default)]
    pub tool: Option<String>,
    #[serde(default)]
    pub tool_call_id: Option<String>,
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionHumanInteraction {
    pub question_id: String,
    pub prompt: String,
    #[serde(default)]
    pub selection_mode: Option<String>,
    #[serde(default)]
    pub options: Option<Vec<AskHumanOption>>,
    #[serde(default)]
    pub answer: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentStreamMessagePayload {
    pub text: String,
    #[serde(default)]
    pub session_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionMessage {
    pub role: String,
    #[serde(default)]
    pub text: Option<String>,
    #[serde(default)]
    pub content: Option<Vec<SessionContentPart>>,
    #[serde(default)]
    pub tool_calls: Option<Vec<SessionToolCall>>,
    #[serde(default)]
    pub tool_result: Option<SessionToolResult>,
    #[serde(default)]
    pub human_interaction: Option<SessionHumanInteraction>,
    #[serde(default)]
    pub tool_call_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentDonePayload {
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub session_ended: Option<bool>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionMetadata {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub message_count: i64,
    pub token_count: i64,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentErrorPayload {
    pub message: String,
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub code: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionDetail {
    pub id: String,
    pub messages: Vec<SessionMessage>,
    pub created_at: String,
    pub updated_at: String,
    pub token_count: i64,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct BridgeConfig {
    pub provider: String,
    pub provider_type: String,
    pub base_url: String,
    pub model: String,
    pub chat_path: String,
    pub api_key_set: bool,
    pub model_selection_enabled: bool,
    pub graphql_default_source: String,
    pub graphql_tool_runtime_enabled: bool,
    pub graphql_text_sanitize_enabled: bool,
    pub graphql_sources: Vec<GraphQLSourceResponse>,
    pub graphql_mutation_policies: Vec<GraphQLMutationPolicyResponse>,
    pub web_rooter_enabled: bool,
    pub web_rooter_api_token_set: bool,
    pub web_search_tavily_url: String,
    pub web_search_exa_url: String,
    pub web_search_tavily_api_key_set: bool,
    pub web_search_exa_api_key_set: bool,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionPushAssistantMessagePayload {
    pub message: String,
    pub session_ended: bool,
    #[serde(default)]
    pub session_end: Option<AssistantSessionEndSignal>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ConfigUpdate {
    #[serde(default)]
    pub provider: Option<String>,
    #[serde(default)]
    pub api_key: Option<String>,
    #[serde(default)]
    pub base_url: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub chat_path: Option<String>,
    #[serde(default)]
    pub graphql_default_source: Option<String>,
    #[serde(default)]
    pub graphql_tool_runtime_enabled: Option<bool>,
    #[serde(default)]
    pub graphql_text_sanitize_enabled: Option<bool>,
    #[serde(default)]
    pub graphql_sources: Option<Vec<GraphQLSourceInput>>,
    #[serde(default)]
    pub graphql_source_upsert: Option<GraphQLSourceInput>,
    #[serde(default)]
    pub graphql_mutation_policies: Option<Vec<GraphQLMutationPolicyInput>>,
    #[serde(default)]
    pub web_rooter_enabled: Option<bool>,
    #[serde(default)]
    pub web_rooter_base_url: Option<String>,
    #[serde(default)]
    pub web_rooter_api_token: Option<String>,
    #[serde(default)]
    pub web_rooter_timeout_ms: Option<i64>,
    #[serde(default)]
    pub web_search_tavily_url: Option<String>,
    #[serde(default)]
    pub web_search_exa_url: Option<String>,
    #[serde(default)]
    pub web_search_tavily_api_key: Option<String>,
    #[serde(default)]
    pub web_search_exa_api_key: Option<String>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SessionPushAwaitingHumanPayload {
    pub question_id: String,
    pub prompt: String,
    #[serde(default)]
    pub selection_mode: Option<String>,
    #[serde(default)]
    pub options: Option<Vec<AskHumanOption>>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct GraphQLDomainResponse {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub root_queries: Vec<String>,
    #[serde(default)]
    pub types: Option<Vec<String>>,
    #[serde(default)]
    pub max_depth: Option<i64>,
    #[serde(default)]
    pub max_fields: Option<i64>,
    #[serde(default)]
    pub max_root_fields: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct GraphQLSourceResponse {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub endpoint: String,
    pub schema_path: String,
    pub timeout_ms: i64,
    pub max_response_bytes: i64,
    pub max_depth: i64,
    pub max_fields: i64,
    pub max_root_fields: i64,
    pub max_fragments: i64,
    #[serde(default)]
    pub headers: Option<BTreeMap<String, String>>,
    pub api_key_set: bool,
    #[serde(default)]
    pub domains: Option<Vec<GraphQLDomainResponse>>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct GraphQLDomainInput {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub root_queries: Vec<String>,
    #[serde(default)]
    pub types: Option<Vec<String>>,
    #[serde(default)]
    pub max_depth: Option<i64>,
    #[serde(default)]
    pub max_fields: Option<i64>,
    #[serde(default)]
    pub max_root_fields: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct GraphQLMutationPolicyResponse {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub source: String,
    pub domain: String,
    pub root_mutation: String,
    #[serde(default)]
    pub approval_required: Option<bool>,
    pub idempotency_mode: String,
    #[serde(default)]
    pub idempotency_header: Option<String>,
    #[serde(default)]
    pub idempotency_variable_path: Option<String>,
    #[serde(default)]
    pub max_depth: Option<i64>,
    #[serde(default)]
    pub max_fields: Option<i64>,
    #[serde(default)]
    pub max_root_fields: Option<i64>,
    #[serde(default)]
    pub max_fragments: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct GraphQLMutationPolicyInput {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub source: String,
    pub domain: String,
    pub root_mutation: String,
    #[serde(default)]
    pub approval_required: Option<bool>,
    pub idempotency_mode: String,
    #[serde(default)]
    pub idempotency_header: Option<String>,
    #[serde(default)]
    pub idempotency_variable_path: Option<String>,
    #[serde(default)]
    pub max_depth: Option<i64>,
    #[serde(default)]
    pub max_fields: Option<i64>,
    #[serde(default)]
    pub max_root_fields: Option<i64>,
    #[serde(default)]
    pub max_fragments: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct GraphQLSourceInput {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub endpoint: String,
    #[serde(default)]
    pub api_key: Option<String>,
    pub schema_path: String,
    #[serde(default)]
    pub timeout_ms: Option<i64>,
    #[serde(default)]
    pub max_response_bytes: Option<i64>,
    #[serde(default)]
    pub headers: Option<BTreeMap<String, String>>,
    #[serde(default)]
    pub max_depth: Option<i64>,
    #[serde(default)]
    pub max_fields: Option<i64>,
    #[serde(default)]
    pub max_root_fields: Option<i64>,
    #[serde(default)]
    pub max_fragments: Option<i64>,
    #[serde(default)]
    pub domains: Option<Vec<GraphQLDomainInput>>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ProviderConfig {
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    pub base_url: String,
    #[serde(default)]
    pub models: Option<Vec<String>>,
    #[serde(default)]
    pub context_window_tokens: Option<i64>,
    #[serde(default)]
    pub response_reserve_tokens: Option<i64>,
    #[serde(default)]
    pub model_context_window_tokens: Option<BTreeMap<String, i64>>,
    #[serde(default)]
    pub model_response_reserve_tokens: Option<BTreeMap<String, i64>>,
    pub api_key_set: bool,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ProviderConfigInput {
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(default)]
    pub base_url: Option<String>,
    #[serde(default)]
    pub api_key: Option<String>,
    #[serde(default)]
    pub models: Option<Vec<String>>,
    #[serde(default)]
    pub context_window_tokens: Option<i64>,
    #[serde(default)]
    pub response_reserve_tokens: Option<i64>,
    #[serde(default)]
    pub model_context_window_tokens: Option<BTreeMap<String, i64>>,
    #[serde(default)]
    pub model_response_reserve_tokens: Option<BTreeMap<String, i64>>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ProviderListResponse {
    pub providers: Vec<ProviderConfig>,
    pub active_provider: String,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct SetActiveProviderRequest {
    pub name: String,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowNode {
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(default)]
    pub tool: Option<WorkflowToolNode>,
    #[serde(default)]
    pub llm: Option<WorkflowLLMNode>,
    #[serde(default)]
    pub agent: Option<WorkflowAgentNode>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowEdge {
    pub from_node_id: String,
    pub to_node_id: String,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowDefinition {
    pub nodes: Vec<WorkflowNode>,
    pub edges: Vec<WorkflowEdge>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct RSSInboxPollTaskActionParams {
    #[serde(default)]
    pub max_items_per_feed: Option<i64>,
    #[serde(default)]
    pub ai_batch_size: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct RSSBriefingTaskActionParams {
    #[serde(default)]
    pub feed_id: Option<String>,
    #[serde(default)]
    pub tag: Option<String>,
    #[serde(default)]
    pub importance: Option<String>,
    #[serde(default)]
    pub window_hours: Option<i64>,
    #[serde(default)]
    pub group_limit: Option<i64>,
    #[serde(default)]
    pub item_limit: Option<i64>,
    #[serde(default)]
    pub items_per_group: Option<i64>,
    #[serde(default)]
    pub highlights_limit: Option<i64>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentMessageTaskCreateRequest {
    pub message: String,
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub task_kind: Option<String>,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowToolNode {
    pub tool_name: String,
    #[serde(default)]
    pub arguments: Option<BTreeMap<String, Value>>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct RSSInboxPollTaskCreateRequest {
    pub task_kind: String,
    pub action: String,
    #[serde(default)]
    pub action_params: Option<RSSInboxPollTaskActionParams>,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowLLMNode {
    pub prompt: String,
    #[serde(default)]
    pub system_prompt: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct RSSBriefingTaskCreateRequest {
    pub task_kind: String,
    pub action: String,
    #[serde(default)]
    pub action_params: Option<RSSBriefingTaskActionParams>,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowAgentNode {
    pub message: String,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowTaskCreateRequest {
    pub task_kind: String,
    pub workflow: WorkflowDefinition,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct TaskUpdateRequest {
    pub id: String,
    #[serde(default)]
    pub message: Option<String>,
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub task_kind: Option<String>,
    #[serde(default)]
    pub action: Option<String>,
    #[serde(default)]
    pub action_params: Option<BTreeMap<String, Value>>,
    #[serde(default)]
    pub workflow: Option<WorkflowDefinition>,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    #[serde(default)]
    pub enabled: Option<bool>,
    #[serde(default)]
    pub trace_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct AgentMessageTaskPayload {
    pub id: String,
    pub message: String,
    #[serde(default)]
    pub session_id: Option<String>,
    pub task_kind: String,
    pub schedule_type: String,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default)]
    pub last_run_at: Option<String>,
    #[serde(default)]
    pub next_run_at: Option<String>,
    #[serde(default)]
    pub last_error: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct RSSInboxPollTaskPayload {
    pub id: String,
    pub task_kind: String,
    pub action: String,
    #[serde(default)]
    pub action_params: Option<RSSInboxPollTaskActionParams>,
    pub schedule_type: String,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default)]
    pub last_run_at: Option<String>,
    #[serde(default)]
    pub next_run_at: Option<String>,
    #[serde(default)]
    pub last_error: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct RSSBriefingTaskPayload {
    pub id: String,
    pub task_kind: String,
    pub action: String,
    #[serde(default)]
    pub action_params: Option<RSSBriefingTaskActionParams>,
    pub schedule_type: String,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default)]
    pub last_run_at: Option<String>,
    #[serde(default)]
    pub next_run_at: Option<String>,
    #[serde(default)]
    pub last_error: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct WorkflowTaskPayload {
    pub id: String,
    pub task_kind: String,
    pub workflow: WorkflowDefinition,
    pub schedule_type: String,
    #[serde(default)]
    pub interval_seconds: Option<i64>,
    #[serde(default)]
    pub cron_expr: Option<String>,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default)]
    pub last_run_at: Option<String>,
    #[serde(default)]
    pub next_run_at: Option<String>,
    #[serde(default)]
    pub last_error: Option<String>,
}

#[derive(Debug, Deserialize, Clone, PartialEq)]
#[serde(untagged)]
pub enum AgentPayload {
    Success(AgentSendSuccessResponse),
    AwaitingHuman(AgentSendAwaitingHumanResponse),
}

#[derive(Debug, Deserialize, Clone, PartialEq)]
#[serde(untagged)]
pub enum TaskCreateRequest {
    AgentMessage(AgentMessageTaskCreateRequest),
    RSSInboxPoll(RSSInboxPollTaskCreateRequest),
    RSSBriefing(RSSBriefingTaskCreateRequest),
    Workflow(WorkflowTaskCreateRequest),
}

#[derive(Debug, Deserialize, Clone, PartialEq)]
#[serde(untagged)]
pub enum TaskPayload {
    AgentMessage(AgentMessageTaskPayload),
    RSSInboxPoll(RSSInboxPollTaskPayload),
    RSSBriefing(RSSBriefingTaskPayload),
    Workflow(WorkflowTaskPayload),
}
